# Generated by oss-policy-kit export-policy (ADR-035). DO NOT EDIT BY HAND.
# Regenerate: oss-policy-kit export-policy --profile github-level-1 --format rego
#
# FIDELITY BOUNDARY (read this):
#   These rules check the kit's OWN output. `input` MUST be an oss-policy-kit
#   evaluation-report.json on the reports/2.0 contract: an object with a
#   `controls` array of {id, state, ...}. The rules assert that every control
#   this profile expects is present and in a passing state. They do NOT
#   re-implement the kit's file/workflow/SARIF analysis (the evaluators) — a
#   static rule cannot reproduce that. Produce the input with:
#     oss-policy-kit evaluate --target <repo> --profile github-level-1 --report-json-contract 2.0
#   Deep semantic validation is OPA's job: `opa check`, `conftest verify`.
#
# Profile: github-level-1 — GitHub OSS starter baseline (level 1)
# Controls: 14 (sorted by id)
package osspolicykit

import rego.v1

# reports/2.0 control states the gate accepts as satisfied (see header).
passing_states := {"PASS", "ATTESTED", "SELF_ATTESTED", "NOT_APPLICABLE"}

# True when control `id` is present in the supplied report with a passing state.
control_satisfied(id) if {
	some c in input.controls
	c.id == id
	c.state in passing_states
}

# --- One deny rule per profile control (sorted by id) ---

# CI-DANGER-007 — No pull_request_target without strong justification [assurance=deterministic]
deny contains msg if {
	not control_satisfied("CI-DANGER-007")
	msg := "CI-DANGER-007 not satisfied: control missing or not in a passing state in the supplied report"
}

# CI-LEAST-009 — Workflow permissions are not obviously over-broad [assurance=signal]
deny contains msg if {
	not control_satisfied("CI-LEAST-009")
	msg := "CI-LEAST-009 not satisfied: control missing or not in a passing state in the supplied report"
}

# CI-PERM-006 — Workflows declare explicit top-level permissions [assurance=deterministic]
deny contains msg if {
	not control_satisfied("CI-PERM-006")
	msg := "CI-PERM-006 not satisfied: control missing or not in a passing state in the supplied report"
}

# CI-PIN-008 — Third-party actions pinned to immutable references [assurance=deterministic]
deny contains msg if {
	not control_satisfied("CI-PIN-008")
	msg := "CI-PIN-008 not satisfied: control missing or not in a passing state in the supplied report"
}

# CI-WF-005 — GitHub Actions workflows exist [assurance=deterministic]
deny contains msg if {
	not control_satisfied("CI-WF-005")
	msg := "CI-WF-005 not satisfied: control missing or not in a passing state in the supplied report"
}

# GOV-CON-002 — CONTRIBUTING guide present [assurance=deterministic]
deny contains msg if {
	not control_satisfied("GOV-CON-002")
	msg := "GOV-CON-002 not satisfied: control missing or not in a passing state in the supplied report"
}

# GOV-COWN-003 — CODEOWNERS configured [assurance=deterministic]
deny contains msg if {
	not control_satisfied("GOV-COWN-003")
	msg := "GOV-COWN-003 not satisfied: control missing or not in a passing state in the supplied report"
}

# GOV-DISC-013 — Responsible disclosure channel documented [assurance=signal]
deny contains msg if {
	not control_satisfied("GOV-DISC-013")
	msg := "GOV-DISC-013 not satisfied: control missing or not in a passing state in the supplied report"
}

# GOV-LIC-004 — LICENSE file present [assurance=deterministic]
deny contains msg if {
	not control_satisfied("GOV-LIC-004")
	msg := "GOV-LIC-004 not satisfied: control missing or not in a passing state in the supplied report"
}

# GOV-SEC-001 — SECURITY.md present [assurance=deterministic]
deny contains msg if {
	not control_satisfied("GOV-SEC-001")
	msg := "GOV-SEC-001 not satisfied: control missing or not in a passing state in the supplied report"
}

# GOV-WAIV-014 — Versioned waiver policy file present in repository (not CLI-only waivers) [assurance=deterministic]
deny contains msg if {
	not control_satisfied("GOV-WAIV-014")
	msg := "GOV-WAIV-014 not satisfied: control missing or not in a passing state in the supplied report"
}

# REL-CHANGE-012 — Changelog or documented release notes [assurance=deterministic]
deny contains msg if {
	not control_satisfied("REL-CHANGE-012")
	msg := "REL-CHANGE-012 not satisfied: control missing or not in a passing state in the supplied report"
}

# SEC-CODEQL-010 — CodeQL or equivalent security scanning in CI [assurance=signal]
deny contains msg if {
	not control_satisfied("SEC-CODEQL-010")
	msg := "SEC-CODEQL-010 not satisfied: control missing or not in a passing state in the supplied report"
}

# SEC-DEPREV-011 — Dependency review in pull requests [assurance=deterministic]
deny contains msg if {
	not control_satisfied("SEC-DEPREV-011")
	msg := "SEC-DEPREV-011 not satisfied: control missing or not in a passing state in the supplied report"
}

# Aggregate gate: allow only when no profile control was denied.
default allow := false

allow if count(deny) == 0
