"""emit-insights --merge: a merge-idempotent Security Insights fragment (T1.2)."""

from __future__ import annotations

import subprocess
import sys
from pathlib import Path

import yaml

from oss_policy_kit.cli.emit_insights import _build_insights_document, _build_insights_fragment

REPO = Path(__file__).parents[2]


def _seed(repo: Path) -> None:
    (repo / "SECURITY.md").write_text("Report vulnerabilities to security@example.com\n", encoding="utf-8")
    (repo / "CONTRIBUTING.md").write_text("# Contributing\n\nThanks!\n", encoding="utf-8")


def test_fragment_drops_volatile_and_assumed_fields(tmp_path: Path) -> None:
    _seed(tmp_path)
    frag = _build_insights_fragment(tmp_path)
    # project-lifecycle is a kit default assumption, not a clone-truth -> dropped.
    assert "project-lifecycle" not in frag
    header = frag.get("header", {})
    # volatile timestamps dropped so the fragment is stable across runs.
    assert "last-updated" not in header
    assert "last-reviewed" not in header
    assert header.get("schema-version")  # stable field kept


def test_fragment_keeps_only_clone_backed_fields(tmp_path: Path) -> None:
    _seed(tmp_path)
    frag = _build_insights_fragment(tmp_path)
    assert "contribution-policy" in frag  # backed by CONTRIBUTING.md
    assert "vulnerability-reporting" in frag  # backed by SECURITY.md


def test_fragment_is_idempotent(tmp_path: Path) -> None:
    _seed(tmp_path)
    a = yaml.safe_dump(_build_insights_fragment(tmp_path), sort_keys=True)
    b = yaml.safe_dump(_build_insights_fragment(tmp_path), sort_keys=True)
    assert a == b


def test_full_document_path_is_unchanged(tmp_path: Path) -> None:
    _seed(tmp_path)
    doc = _build_insights_document(tmp_path)
    # The full standalone document still carries the scaffolding + timestamps.
    assert "project-lifecycle" in doc
    assert "last-updated" in doc["header"]


def test_cli_merge_writes_idempotent_fragment(tmp_path: Path) -> None:
    out1 = tmp_path / "frag1.yml"
    out2 = tmp_path / "frag2.yml"
    for out in (out1, out2):
        subprocess.run(
            [
                sys.executable,
                "-m",
                "oss_policy_kit",
                "emit-insights",
                "--target",
                str(REPO),
                "--merge",
                "--output",
                str(out),
            ],
            cwd=REPO,
            capture_output=True,
            text=True,
            encoding="utf-8",
            errors="replace",
            timeout=120,
            check=False,
        )
    text1 = out1.read_text(encoding="utf-8")
    assert "fragment generated by" in text1  # banner present
    assert "last-updated" not in text1
    assert text1 == out2.read_text(encoding="utf-8")  # byte-idempotent


def test_cli_default_still_emits_full_document(tmp_path: Path) -> None:
    out = tmp_path / "full.yml"
    subprocess.run(
        [sys.executable, "-m", "oss_policy_kit", "emit-insights", "--target", str(REPO), "--output", str(out)],
        cwd=REPO,
        capture_output=True,
        text=True,
        encoding="utf-8",
        errors="replace",
        timeout=120,
        check=False,
    )
    doc = yaml.safe_load(out.read_text(encoding="utf-8"))
    assert "project-lifecycle" in doc  # full doc unchanged by the --merge addition
