export const navSections = [
  { id: "hero", label: "Overview" },
  { id: "problem", label: "Problem" },
  { id: "scope", label: "Scope" },
  { id: "flow", label: "Workflow" },
  { id: "quickstart", label: "Quickstart" },
  { id: "capabilities", label: "Capabilities" },
  { id: "profiles", label: "Profiles" },
  { id: "states", label: "Evaluation" },
  { id: "differentiators", label: "Why this kit" },
  { id: "examples", label: "Signals" },
  { id: "roadmap", label: "Roadmap" },
  { id: "architecture", label: "Repository" },
  { id: "cta", label: "Get started" },
] as const;
