// Interactive control catalog explorer — client-side filterable view of the
// full bundled catalog. Reads window.CATALOG_DATA (generated by
// scripts/generate-gitpage-catalog-data.py). useState/useMemo are already in
// scope from primitives.jsx — do not redeclare.

const _CATALOG_FALLBACK = {
  controlCount: 0,
  profileCount: 0,
  facets: { categories: [], assurances: [], lifecycles: [], profiles: [] },
  controls: [],
};

const _CATEGORY_LABELS = {
  ci_cd: "CI/CD",
  iac: "IaC",
  secure_development: "Secure dev",
  supply_chain: "Supply chain",
  vulnerability_management: "Vuln mgmt",
};

function prettyCategory(cat) {
  if (_CATEGORY_LABELS[cat]) return _CATEGORY_LABELS[cat];
  return cat
    .split("_")
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join(" ");
}

function assuranceStyle(assurance) {
  switch (assurance) {
    case "deterministic":
      return "border-signal/40 bg-signal/10 text-signal";
    case "evidence-backed":
      return "border-sky-400/40 bg-sky-400/10 text-sky-300";
    default: // signal
      return "border-amber-400/40 bg-amber-400/10 text-amber-300";
  }
}

function lifecycleStyle(lifecycle) {
  switch (lifecycle) {
    case "stable":
      return "text-mist";
    case "deprecated":
      return "text-rose-300";
    default: // experimental
      return "text-steel";
  }
}

function CatalogChip({ label, active, onClick, hint }) {
  return (
    <button
      type="button"
      onClick={onClick}
      aria-pressed={active}
      className={`inline-flex items-center gap-1.5 rounded-lg border px-3 py-1.5 text-xs font-medium transition ${
        active
          ? "border-signal/45 bg-signal/15 text-signal"
          : "border-white/10 bg-white/[0.03] text-slate hover:border-white/25 hover:text-mist"
      }`}
    >
      {label}
      {hint != null && (
        <span className={`font-mono text-[10px] ${active ? "text-signal/80" : "text-steel"}`}>
          {hint}
        </span>
      )}
    </button>
  );
}

function ControlCatalogSection() {
  const data =
    (typeof window !== "undefined" && window.CATALOG_DATA) || _CATALOG_FALLBACK;
  const facets = data.facets || _CATALOG_FALLBACK.facets;

  const [query, setQuery] = useState("");
  const [cats, setCats] = useState(() => new Set());
  const [asr, setAsr] = useState(() => new Set());
  const [life, setLife] = useState(() => new Set());
  const [profile, setProfile] = useState("");

  const toggleIn = (setFn) => (value) =>
    setFn((prev) => {
      const next = new Set(prev);
      if (next.has(value)) next.delete(value);
      else next.add(value);
      return next;
    });

  // Per-category counts so chips can show how many controls each facet holds.
  const catCounts = useMemo(() => {
    const m = {};
    data.controls.forEach((c) => {
      m[c.category] = (m[c.category] || 0) + 1;
    });
    return m;
  }, [data]);

  const filtered = useMemo(() => {
    const q = query.trim().toLowerCase();
    return data.controls.filter((c) => {
      if (cats.size && !cats.has(c.category)) return false;
      if (asr.size && !asr.has(c.assurance)) return false;
      if (life.size && !life.has(c.lifecycle)) return false;
      if (profile && !(c.profiles || []).includes(profile)) return false;
      if (q && !(c.id.toLowerCase().includes(q) || c.title.toLowerCase().includes(q)))
        return false;
      return true;
    });
  }, [data, query, cats, asr, life, profile]);

  const activeCount =
    cats.size + asr.size + life.size + (profile ? 1 : 0) + (query.trim() ? 1 : 0);

  const reset = () => {
    setQuery("");
    setCats(new Set());
    setAsr(new Set());
    setLife(new Set());
    setProfile("");
  };

  return (
    <SectionShell
      id="catalog"
      eyebrow="Control catalog"
      title={`Browse every one of the ${data.controlCount} controls`}
      subtitle="Filter the full bundled catalog by family, assurance grade, lifecycle, or profile membership. Data is generated from the authoritative catalog and profiles, so this view never drifts from a release."
    >
      <Reveal>
        <div className="glass rounded-2xl p-5 md:p-6">
          {/* Search */}
          <label className="relative block">
            <span className="sr-only">Search controls by ID or title</span>
            <span className="pointer-events-none absolute left-3 top-1/2 -translate-y-1/2 text-steel">
              <Icon name="scan" className="h-4 w-4" />
            </span>
            <input
              type="text"
              value={query}
              onChange={(e) => setQuery(e.target.value)}
              placeholder="Search by control ID or title…"
              className="w-full rounded-xl border border-white/10 bg-ink-deep/60 py-2.5 pl-10 pr-4 text-sm text-mist placeholder:text-steel focus:border-signal/45 focus:outline-none focus:ring-1 focus:ring-signal/30"
            />
          </label>

          {/* Family chips */}
          <div className="mt-5">
            <p className="mb-2 text-[11px] font-semibold uppercase tracking-wider text-steel">
              Family
            </p>
            <div className="flex flex-wrap gap-2">
              {facets.categories.map((c) => (
                <CatalogChip
                  key={c}
                  label={prettyCategory(c)}
                  hint={catCounts[c]}
                  active={cats.has(c)}
                  onClick={() => toggleIn(setCats)(c)}
                />
              ))}
            </div>
          </div>

          {/* Assurance + Lifecycle */}
          <div className="mt-5 grid gap-5 sm:grid-cols-2">
            <div>
              <p className="mb-2 text-[11px] font-semibold uppercase tracking-wider text-steel">
                Assurance
              </p>
              <div className="flex flex-wrap gap-2">
                {facets.assurances.map((a) => (
                  <CatalogChip
                    key={a}
                    label={a}
                    active={asr.has(a)}
                    onClick={() => toggleIn(setAsr)(a)}
                  />
                ))}
              </div>
            </div>
            <div>
              <p className="mb-2 text-[11px] font-semibold uppercase tracking-wider text-steel">
                Lifecycle
              </p>
              <div className="flex flex-wrap gap-2">
                {facets.lifecycles.map((l) => (
                  <CatalogChip
                    key={l}
                    label={l}
                    active={life.has(l)}
                    onClick={() => toggleIn(setLife)(l)}
                  />
                ))}
              </div>
            </div>
          </div>

          {/* Profile select + reset */}
          <div className="mt-5 flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between">
            <label className="block sm:max-w-xs sm:flex-1">
              <span className="mb-2 block text-[11px] font-semibold uppercase tracking-wider text-steel">
                Profile membership
              </span>
              <select
                value={profile}
                onChange={(e) => setProfile(e.target.value)}
                className="w-full rounded-xl border border-white/10 bg-ink-deep/60 px-3 py-2.5 text-sm text-mist focus:border-signal/45 focus:outline-none focus:ring-1 focus:ring-signal/30"
              >
                <option value="">All {data.profileCount} profiles</option>
                {facets.profiles.map((p) => (
                  <option key={p} value={p}>
                    {p}
                  </option>
                ))}
              </select>
            </label>
            <div className="flex items-center gap-3 text-sm">
              <span className="text-slate">
                <span className="font-mono text-mist">{filtered.length}</span> of{" "}
                <span className="font-mono">{data.controlCount}</span> controls
              </span>
              <button
                type="button"
                onClick={reset}
                disabled={activeCount === 0}
                className={`rounded-lg border px-3 py-1.5 text-xs font-medium transition ${
                  activeCount === 0
                    ? "cursor-not-allowed border-white/5 text-steel/50"
                    : "border-white/15 text-slate hover:border-signal/40 hover:text-mist"
                }`}
              >
                Reset{activeCount ? ` (${activeCount})` : ""}
              </button>
            </div>
          </div>
        </div>
      </Reveal>

      {/* Results table */}
      <Reveal delay={80}>
        <div className="mt-6 overflow-hidden rounded-2xl border border-white/10 bg-ink-deep/40">
          <div className="max-h-[28rem] overflow-y-auto">
            <table className="w-full border-collapse text-left text-sm">
              <thead className="sticky top-0 z-10 bg-ink-deep/95 backdrop-blur">
                <tr className="text-[11px] uppercase tracking-wider text-steel">
                  <th className="px-4 py-3 font-semibold">Control</th>
                  <th className="hidden px-4 py-3 font-semibold md:table-cell">Family</th>
                  <th className="px-4 py-3 font-semibold">Assurance</th>
                  <th className="hidden px-4 py-3 font-semibold sm:table-cell">Lifecycle</th>
                  <th className="px-4 py-3 text-right font-semibold">Profiles</th>
                </tr>
              </thead>
              <tbody>
                {filtered.length === 0 && (
                  <tr>
                    <td colSpan={5} className="px-4 py-10 text-center text-slate">
                      No controls match the current filters.
                    </td>
                  </tr>
                )}
                {filtered.map((c) => (
                  <tr
                    key={c.id}
                    className="border-t border-white/5 transition hover:bg-white/[0.03]"
                  >
                    <td className="px-4 py-3 align-top">
                      <div className="font-mono text-xs text-signal">{c.id}</div>
                      <div className="mt-0.5 max-w-md text-[13px] leading-snug text-mist">
                        {c.title}
                      </div>
                      <div className="mt-1 text-[11px] text-steel md:hidden">
                        {prettyCategory(c.category)}
                      </div>
                    </td>
                    <td className="hidden px-4 py-3 align-top text-xs text-slate md:table-cell">
                      {prettyCategory(c.category)}
                    </td>
                    <td className="px-4 py-3 align-top">
                      <span
                        className={`inline-flex rounded-md border px-2 py-0.5 text-[11px] font-medium ${assuranceStyle(
                          c.assurance
                        )}`}
                      >
                        {c.assurance}
                      </span>
                    </td>
                    <td
                      className={`hidden px-4 py-3 align-top text-xs sm:table-cell ${lifecycleStyle(
                        c.lifecycle
                      )}`}
                    >
                      {c.lifecycle}
                    </td>
                    <td className="px-4 py-3 text-right align-top">
                      <span
                        className={`font-mono text-xs ${
                          c.profiles.length ? "text-mist" : "text-steel"
                        }`}
                        title={
                          c.profiles.length
                            ? c.profiles.join(", ")
                            : "Not bundled in any profile"
                        }
                      >
                        {c.profiles.length}
                      </span>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>
      </Reveal>

      <Reveal delay={140}>
        <p className="mt-4 text-xs text-steel">
          Hover a profile count to see membership. For the full reference see{" "}
          <a
            href={`${DOCS_URL}/controls-catalog.md`}
            target="_blank"
            rel="noreferrer noopener"
            className="text-slate underline decoration-white/20 underline-offset-2 hover:text-signal"
          >
            controls-catalog.md
          </a>
          .
        </p>
      </Reveal>
    </SectionShell>
  );
}

window.ControlCatalogSection = ControlCatalogSection;
