// AUTO-GENERATED by scripts/generate-gitpage-catalog-data.py — do not edit by hand.
// Regenerate with: python scripts/generate-gitpage-catalog-data.py
// Source of truth: src/oss_policy_kit/data/controls/catalog.yaml + bundled profiles.
window.CATALOG_DATA = {
  "controlCount": 221,
  "profileCount": 56,
  "facets": {
    "categories": [
      "ci_cd",
      "container",
      "governance",
      "iac",
      "kubernetes",
      "platform",
      "release",
      "secure_development",
      "supply_chain",
      "vulnerability_management"
    ],
    "assurances": [
      "deterministic",
      "evidence-backed",
      "signal"
    ],
    "lifecycles": [
      "stable",
      "experimental"
    ],
    "profiles": [
      "ai-agent-baseline-1",
      "appsec-agentic-asi-1",
      "appsec-llm-ssdf-218a-1",
      "appsec-mcp-server-1",
      "appsec-sast-sca-1",
      "aws-level-1",
      "aws-level-2",
      "aws-level-3",
      "aws-release-hardening-1",
      "aws-release-hardening-2",
      "aws-release-hardening-3",
      "azure-level-1",
      "azure-level-2",
      "azure-level-3",
      "azure-release-hardening-1",
      "azure-release-hardening-2",
      "azure-release-hardening-3",
      "cis-supply-chain-1",
      "container-baseline-1",
      "cra-eu-ai-act-art11-1",
      "cra-eu-ready-1",
      "cra-eu-ready-2-1",
      "cra-eu-reporting-1",
      "cra-eu-strict-1",
      "github-aws-level-2",
      "github-azure-level-2",
      "github-level-1",
      "github-level-2",
      "github-level-3",
      "github-release-hardening-1",
      "github-release-hardening-2",
      "github-release-hardening-3",
      "gitlab-level-1",
      "gitlab-level-2",
      "gitlab-level-3",
      "gitlab-release-hardening-1",
      "gitlab-release-hardening-2",
      "gitlab-release-hardening-3",
      "iac-bicep-baseline-1",
      "iac-cfn-baseline-1",
      "iac-pulumi-baseline-1",
      "iac-terraform-baseline-1",
      "kubernetes-baseline-1",
      "osps-baseline-1",
      "osps-baseline-2026-1",
      "oss-publish-readiness-1",
      "owasp-cicd-top10-1",
      "s2c2f-l1-1",
      "s2c2f-l2-1",
      "s2c2f-l3-1",
      "slsa-build-l2-1",
      "slsa-source-l1-1",
      "slsa-source-l2-1",
      "ssdf-baseline-1",
      "webhook-security-1",
      "webhook-security-2"
    ]
  },
  "controls": [
    {
      "id": "GOV-SEC-001",
      "title": "SECURITY.md present",
      "category": "governance",
      "assurance": "deterministic",
      "lifecycle": "stable",
      "weight": 3,
      "profiles": [
        "appsec-agentic-asi-1",
        "appsec-llm-ssdf-218a-1",
        "appsec-mcp-server-1",
        "aws-level-1",
        "aws-level-2",
        "aws-level-3",
        "aws-release-hardening-1",
        "aws-release-hardening-2",
        "aws-release-hardening-3",
        "azure-level-1",
        "azure-level-2",
        "azure-level-3",
        "azure-release-hardening-1",
        "azure-release-hardening-2",
        "azure-release-hardening-3",
        "cra-eu-ai-act-art11-1",
        "cra-eu-ready-1",
        "cra-eu-ready-2-1",
        "cra-eu-reporting-1",
        "cra-eu-strict-1",
        "github-aws-level-2",
        "github-azure-level-2",
        "github-level-1",
        "github-level-2",
        "github-level-3",
        "github-release-hardening-1",
        "github-release-hardening-2",
        "github-release-hardening-3",
        "gitlab-level-1",
        "gitlab-level-2",
        "gitlab-level-3",
        "gitlab-release-hardening-1",
        "gitlab-release-hardening-2",
        "gitlab-release-hardening-3",
        "osps-baseline-1",
        "osps-baseline-2026-1",
        "oss-publish-readiness-1",
        "s2c2f-l1-1",
        "s2c2f-l2-1",
        "s2c2f-l3-1",
        "slsa-build-l2-1",
        "slsa-source-l1-1",
        "slsa-source-l2-1",
        "ssdf-baseline-1",
        "webhook-security-2"
      ]
    },
    {
      "id": "GOV-CON-002",
      "title": "CONTRIBUTING guide present",
      "category": "governance",
      "assurance": "deterministic",
      "lifecycle": "stable",
      "weight": 1,
      "profiles": [
        "aws-level-1",
        "aws-level-2",
        "aws-level-3",
        "aws-release-hardening-1",
        "aws-release-hardening-2",
        "aws-release-hardening-3",
        "azure-level-1",
        "azure-level-2",
        "azure-level-3",
        "azure-release-hardening-1",
        "azure-release-hardening-2",
        "azure-release-hardening-3",
        "github-aws-level-2",
        "github-azure-level-2",
        "github-level-1",
        "github-level-2",
        "github-level-3",
        "github-release-hardening-1",
        "github-release-hardening-2",
        "github-release-hardening-3",
        "gitlab-level-1",
        "gitlab-level-2",
        "gitlab-level-3",
        "gitlab-release-hardening-1",
        "gitlab-release-hardening-2",
        "gitlab-release-hardening-3",
        "osps-baseline-1",
        "osps-baseline-2026-1",
        "ssdf-baseline-1"
      ]
    },
    {
      "id": "GOV-COWN-003",
      "title": "CODEOWNERS configured",
      "category": "governance",
      "assurance": "deterministic",
      "lifecycle": "stable",
      "weight": 2,
      "profiles": [
        "aws-level-1",
        "aws-level-2",
        "aws-level-3",
        "aws-release-hardening-1",
        "aws-release-hardening-2",
        "aws-release-hardening-3",
        "azure-level-1",
        "azure-level-2",
        "azure-level-3",
        "azure-release-hardening-1",
        "azure-release-hardening-2",
        "azure-release-hardening-3",
        "cis-supply-chain-1",
        "github-aws-level-2",
        "github-azure-level-2",
        "github-level-1",
        "github-level-2",
        "github-level-3",
        "github-release-hardening-1",
        "github-release-hardening-2",
        "github-release-hardening-3",
        "gitlab-level-1",
        "gitlab-level-2",
        "gitlab-level-3",
        "gitlab-release-hardening-1",
        "gitlab-release-hardening-2",
        "gitlab-release-hardening-3",
        "osps-baseline-1",
        "osps-baseline-2026-1",
        "owasp-cicd-top10-1",
        "ssdf-baseline-1"
      ]
    },
    {
      "id": "GOV-LIC-004",
      "title": "LICENSE file present",
      "category": "governance",
      "assurance": "deterministic",
      "lifecycle": "stable",
      "weight": 1,
      "profiles": [
        "aws-level-1",
        "aws-level-2",
        "aws-level-3",
        "aws-release-hardening-1",
        "aws-release-hardening-2",
        "aws-release-hardening-3",
        "azure-level-1",
        "azure-level-2",
        "azure-level-3",
        "azure-release-hardening-1",
        "azure-release-hardening-2",
        "azure-release-hardening-3",
        "github-aws-level-2",
        "github-azure-level-2",
        "github-level-1",
        "github-level-2",
        "github-level-3",
        "github-release-hardening-1",
        "github-release-hardening-2",
        "github-release-hardening-3",
        "gitlab-level-1",
        "gitlab-level-2",
        "gitlab-level-3",
        "gitlab-release-hardening-1",
        "gitlab-release-hardening-2",
        "gitlab-release-hardening-3",
        "osps-baseline-1",
        "osps-baseline-2026-1",
        "s2c2f-l2-1",
        "s2c2f-l3-1",
        "slsa-build-l2-1",
        "ssdf-baseline-1"
      ]
    },
    {
      "id": "CI-WF-005",
      "title": "GitHub Actions workflows exist",
      "category": "ci_cd",
      "assurance": "deterministic",
      "lifecycle": "stable",
      "weight": 2,
      "profiles": [
        "cis-supply-chain-1",
        "github-aws-level-2",
        "github-azure-level-2",
        "github-level-1",
        "github-level-2",
        "github-level-3",
        "github-release-hardening-1",
        "github-release-hardening-2",
        "github-release-hardening-3",
        "osps-baseline-1",
        "osps-baseline-2026-1",
        "slsa-build-l2-1"
      ]
    },
    {
      "id": "CI-PERM-006",
      "title": "Workflows declare explicit top-level permissions",
      "category": "ci_cd",
      "assurance": "deterministic",
      "lifecycle": "stable",
      "weight": 3,
      "profiles": [
        "cis-supply-chain-1",
        "github-aws-level-2",
        "github-azure-level-2",
        "github-level-1",
        "github-level-2",
        "github-level-3",
        "github-release-hardening-1",
        "github-release-hardening-2",
        "github-release-hardening-3",
        "osps-baseline-1",
        "osps-baseline-2026-1",
        "oss-publish-readiness-1",
        "owasp-cicd-top10-1",
        "slsa-build-l2-1"
      ]
    },
    {
      "id": "CI-DANGER-007",
      "title": "No pull_request_target without strong justification",
      "category": "ci_cd",
      "assurance": "deterministic",
      "lifecycle": "stable",
      "weight": 3,
      "profiles": [
        "cis-supply-chain-1",
        "github-aws-level-2",
        "github-azure-level-2",
        "github-level-1",
        "github-level-2",
        "github-level-3",
        "github-release-hardening-1",
        "github-release-hardening-2",
        "github-release-hardening-3",
        "owasp-cicd-top10-1"
      ]
    },
    {
      "id": "CI-PIN-008",
      "title": "Third-party actions pinned to immutable references",
      "category": "supply_chain",
      "assurance": "deterministic",
      "lifecycle": "stable",
      "weight": 3,
      "profiles": [
        "appsec-sast-sca-1",
        "cis-supply-chain-1",
        "cra-eu-strict-1",
        "github-aws-level-2",
        "github-azure-level-2",
        "github-level-1",
        "github-level-2",
        "github-level-3",
        "github-release-hardening-1",
        "github-release-hardening-2",
        "github-release-hardening-3",
        "osps-baseline-1",
        "osps-baseline-2026-1",
        "oss-publish-readiness-1",
        "owasp-cicd-top10-1",
        "s2c2f-l1-1",
        "s2c2f-l2-1",
        "s2c2f-l3-1",
        "slsa-build-l2-1",
        "ssdf-baseline-1"
      ]
    },
    {
      "id": "CI-LEAST-009",
      "title": "Workflow permissions are not obviously over-broad",
      "category": "ci_cd",
      "assurance": "signal",
      "lifecycle": "stable",
      "weight": 2,
      "profiles": [
        "cis-supply-chain-1",
        "github-aws-level-2",
        "github-azure-level-2",
        "github-level-1",
        "github-level-2",
        "github-level-3",
        "github-release-hardening-1",
        "github-release-hardening-2",
        "github-release-hardening-3",
        "owasp-cicd-top10-1"
      ]
    },
    {
      "id": "SEC-CODEQL-010",
      "title": "CodeQL or equivalent security scanning in CI",
      "category": "vulnerability_management",
      "assurance": "signal",
      "lifecycle": "stable",
      "weight": 2,
      "profiles": [
        "appsec-sast-sca-1",
        "github-aws-level-2",
        "github-azure-level-2",
        "github-level-1",
        "github-level-2",
        "github-level-3",
        "github-release-hardening-1",
        "github-release-hardening-2",
        "github-release-hardening-3",
        "osps-baseline-1",
        "osps-baseline-2026-1",
        "ssdf-baseline-1"
      ]
    },
    {
      "id": "SEC-DEPREV-011",
      "title": "Dependency review in pull requests",
      "category": "supply_chain",
      "assurance": "deterministic",
      "lifecycle": "stable",
      "weight": 2,
      "profiles": [
        "appsec-sast-sca-1",
        "cis-supply-chain-1",
        "cra-eu-ready-1",
        "cra-eu-reporting-1",
        "cra-eu-strict-1",
        "github-aws-level-2",
        "github-azure-level-2",
        "github-level-1",
        "github-level-2",
        "github-level-3",
        "github-release-hardening-1",
        "github-release-hardening-2",
        "github-release-hardening-3",
        "gitlab-level-1",
        "gitlab-level-2",
        "gitlab-level-3",
        "gitlab-release-hardening-1",
        "gitlab-release-hardening-2",
        "gitlab-release-hardening-3",
        "osps-baseline-1",
        "osps-baseline-2026-1",
        "owasp-cicd-top10-1",
        "s2c2f-l1-1",
        "s2c2f-l2-1",
        "s2c2f-l3-1",
        "ssdf-baseline-1"
      ]
    },
    {
      "id": "REL-CHANGE-012",
      "title": "Changelog or documented release notes",
      "category": "release",
      "assurance": "deterministic",
      "lifecycle": "stable",
      "weight": 1,
      "profiles": [
        "aws-level-1",
        "aws-level-2",
        "aws-level-3",
        "aws-release-hardening-1",
        "aws-release-hardening-2",
        "aws-release-hardening-3",
        "azure-level-1",
        "azure-level-2",
        "azure-level-3",
        "azure-release-hardening-1",
        "azure-release-hardening-2",
        "azure-release-hardening-3",
        "cra-eu-ai-act-art11-1",
        "cra-eu-ready-1",
        "cra-eu-ready-2-1",
        "cra-eu-reporting-1",
        "cra-eu-strict-1",
        "github-aws-level-2",
        "github-azure-level-2",
        "github-level-1",
        "github-level-2",
        "github-level-3",
        "github-release-hardening-1",
        "github-release-hardening-2",
        "github-release-hardening-3",
        "gitlab-level-1",
        "gitlab-level-2",
        "gitlab-level-3",
        "gitlab-release-hardening-1",
        "gitlab-release-hardening-2",
        "gitlab-release-hardening-3",
        "osps-baseline-1",
        "osps-baseline-2026-1",
        "slsa-build-l2-1"
      ]
    },
    {
      "id": "GOV-BUILD-072",
      "title": "Source-code build instructions documented",
      "category": "governance",
      "assurance": "signal",
      "lifecycle": "experimental",
      "weight": 1,
      "profiles": [
        "osps-baseline-2026-1"
      ]
    },
    {
      "id": "GOV-DISC-013",
      "title": "Responsible disclosure channel documented",
      "category": "governance",
      "assurance": "signal",
      "lifecycle": "stable",
      "weight": 2,
      "profiles": [
        "appsec-agentic-asi-1",
        "appsec-llm-ssdf-218a-1",
        "appsec-mcp-server-1",
        "aws-level-1",
        "aws-level-2",
        "aws-level-3",
        "aws-release-hardening-1",
        "aws-release-hardening-2",
        "aws-release-hardening-3",
        "azure-level-1",
        "azure-level-2",
        "azure-level-3",
        "azure-release-hardening-1",
        "azure-release-hardening-2",
        "azure-release-hardening-3",
        "cra-eu-ai-act-art11-1",
        "cra-eu-ready-1",
        "cra-eu-ready-2-1",
        "cra-eu-reporting-1",
        "cra-eu-strict-1",
        "github-aws-level-2",
        "github-azure-level-2",
        "github-level-1",
        "github-level-2",
        "github-level-3",
        "github-release-hardening-1",
        "github-release-hardening-2",
        "github-release-hardening-3",
        "gitlab-level-1",
        "gitlab-level-2",
        "gitlab-level-3",
        "gitlab-release-hardening-1",
        "gitlab-release-hardening-2",
        "gitlab-release-hardening-3",
        "osps-baseline-1",
        "osps-baseline-2026-1",
        "oss-publish-readiness-1",
        "s2c2f-l1-1",
        "s2c2f-l2-1",
        "s2c2f-l3-1",
        "slsa-source-l1-1",
        "slsa-source-l2-1",
        "ssdf-baseline-1",
        "webhook-security-2"
      ]
    },
    {
      "id": "GOV-WAIV-014",
      "title": "Versioned waiver policy file present in repository (not CLI-only waivers)",
      "category": "governance",
      "assurance": "deterministic",
      "lifecycle": "stable",
      "weight": 1,
      "profiles": [
        "appsec-agentic-asi-1",
        "appsec-llm-ssdf-218a-1",
        "appsec-mcp-server-1",
        "appsec-sast-sca-1",
        "aws-level-1",
        "aws-level-2",
        "aws-level-3",
        "aws-release-hardening-1",
        "aws-release-hardening-2",
        "aws-release-hardening-3",
        "azure-level-1",
        "azure-level-2",
        "azure-level-3",
        "azure-release-hardening-1",
        "azure-release-hardening-2",
        "azure-release-hardening-3",
        "cra-eu-ai-act-art11-1",
        "cra-eu-ready-1",
        "cra-eu-ready-2-1",
        "cra-eu-reporting-1",
        "cra-eu-strict-1",
        "github-aws-level-2",
        "github-azure-level-2",
        "github-level-1",
        "github-level-2",
        "github-level-3",
        "github-release-hardening-1",
        "github-release-hardening-2",
        "github-release-hardening-3",
        "gitlab-level-1",
        "gitlab-level-2",
        "gitlab-level-3",
        "gitlab-release-hardening-1",
        "gitlab-release-hardening-2",
        "gitlab-release-hardening-3",
        "oss-publish-readiness-1",
        "s2c2f-l1-1",
        "s2c2f-l2-1",
        "s2c2f-l3-1",
        "slsa-source-l1-1",
        "slsa-source-l2-1",
        "ssdf-baseline-1"
      ]
    },
    {
      "id": "PLAT-BRPROT-015",
      "title": "Default branch protection / rulesets (evidence-backed)",
      "category": "platform",
      "assurance": "evidence-backed",
      "lifecycle": "stable",
      "weight": 3,
      "profiles": [
        "cis-supply-chain-1",
        "cra-eu-ready-1",
        "cra-eu-strict-1",
        "github-release-hardening-1",
        "github-release-hardening-2",
        "github-release-hardening-3",
        "gitlab-level-3",
        "gitlab-release-hardening-1",
        "gitlab-release-hardening-2",
        "gitlab-release-hardening-3",
        "osps-baseline-1",
        "osps-baseline-2026-1",
        "owasp-cicd-top10-1",
        "ssdf-baseline-1"
      ]
    },
    {
      "id": "GH-WF-018",
      "title": "Reusable workflows avoid secrets inherit",
      "category": "ci_cd",
      "assurance": "deterministic",
      "lifecycle": "stable",
      "weight": 2,
      "profiles": [
        "cis-supply-chain-1",
        "github-aws-level-2",
        "github-azure-level-2",
        "github-level-2",
        "github-level-3",
        "github-release-hardening-2",
        "github-release-hardening-3",
        "owasp-cicd-top10-1",
        "slsa-build-l2-1"
      ]
    },
    {
      "id": "GH-WF-019",
      "title": "PR-triggered workflows avoid self-hosted runners",
      "category": "ci_cd",
      "assurance": "deterministic",
      "lifecycle": "stable",
      "weight": 2,
      "profiles": [
        "cis-supply-chain-1",
        "github-aws-level-2",
        "github-azure-level-2",
        "github-level-2",
        "github-level-3",
        "github-release-hardening-2",
        "github-release-hardening-3",
        "owasp-cicd-top10-1",
        "slsa-build-l2-1"
      ]
    },
    {
      "id": "GH-WF-020",
      "title": "Job-level permissions avoid broad write scopes",
      "category": "ci_cd",
      "assurance": "deterministic",
      "lifecycle": "stable",
      "weight": 2,
      "profiles": [
        "github-aws-level-2",
        "github-azure-level-2",
        "github-level-2",
        "github-level-3",
        "github-release-hardening-2",
        "github-release-hardening-3",
        "owasp-cicd-top10-1",
        "slsa-build-l2-1"
      ]
    },
    {
      "id": "GH-REL-021",
      "title": "Release/deploy workflows declare concurrency controls",
      "category": "release",
      "assurance": "signal",
      "lifecycle": "stable",
      "weight": 1,
      "profiles": [
        "cis-supply-chain-1",
        "github-aws-level-2",
        "github-azure-level-2",
        "github-level-2",
        "github-level-3",
        "github-release-hardening-2",
        "github-release-hardening-3"
      ]
    },
    {
      "id": "GH-DEPLOY-022",
      "title": "Cloud deployment workflows show OIDC posture",
      "category": "platform",
      "assurance": "signal",
      "lifecycle": "stable",
      "weight": 2,
      "profiles": [
        "cis-supply-chain-1",
        "github-aws-level-2",
        "github-azure-level-2",
        "github-level-2",
        "github-release-hardening-2"
      ]
    },
    {
      "id": "GH-PROV-023",
      "title": "Build provenance or artifact attestation signal in workflows (with optional verification-block confirmation)",
      "category": "supply_chain",
      "assurance": "evidence-backed",
      "lifecycle": "stable",
      "weight": 2,
      "profiles": [
        "cis-supply-chain-1",
        "cra-eu-strict-1",
        "github-aws-level-2",
        "github-azure-level-2",
        "github-level-2",
        "github-release-hardening-2",
        "osps-baseline-1",
        "osps-baseline-2026-1",
        "owasp-cicd-top10-1",
        "s2c2f-l3-1",
        "slsa-build-l2-1",
        "ssdf-baseline-1"
      ]
    },
    {
      "id": "GH-PLAT-024",
      "title": "GitHub rulesets posture evidenced",
      "category": "platform",
      "assurance": "evidence-backed",
      "lifecycle": "stable",
      "weight": 3,
      "profiles": [
        "cis-supply-chain-1",
        "cra-eu-strict-1",
        "github-level-3",
        "github-release-hardening-2",
        "github-release-hardening-3",
        "osps-baseline-1",
        "osps-baseline-2026-1",
        "owasp-cicd-top10-1",
        "ssdf-baseline-1"
      ]
    },
    {
      "id": "GH-PLAT-025",
      "title": "GitHub environment protection posture evidenced",
      "category": "platform",
      "assurance": "evidence-backed",
      "lifecycle": "stable",
      "weight": 3,
      "profiles": [
        "cis-supply-chain-1",
        "cra-eu-strict-1",
        "github-level-3",
        "github-release-hardening-2",
        "github-release-hardening-3",
        "owasp-cicd-top10-1",
        "ssdf-baseline-1"
      ]
    },
    {
      "id": "GH-PLAT-026",
      "title": "GitHub secret scanning posture evidenced",
      "category": "platform",
      "assurance": "evidence-backed",
      "lifecycle": "stable",
      "weight": 2,
      "profiles": [
        "appsec-sast-sca-1",
        "cis-supply-chain-1",
        "cra-eu-strict-1",
        "github-level-3",
        "github-release-hardening-2",
        "github-release-hardening-3",
        "owasp-cicd-top10-1",
        "ssdf-baseline-1"
      ]
    },
    {
      "id": "AZ-PIPE-027",
      "title": "Azure Pipelines definitions exist in supported paths",
      "category": "ci_cd",
      "assurance": "deterministic",
      "lifecycle": "stable",
      "weight": 2,
      "profiles": [
        "azure-level-1",
        "azure-level-2",
        "azure-level-3",
        "azure-release-hardening-1",
        "azure-release-hardening-2",
        "azure-release-hardening-3",
        "github-azure-level-2"
      ]
    },
    {
      "id": "AZ-PIPE-028",
      "title": "Azure Pipelines include pull request validation trigger posture",
      "category": "ci_cd",
      "assurance": "deterministic",
      "lifecycle": "stable",
      "weight": 2,
      "profiles": [
        "azure-level-1",
        "azure-level-2",
        "azure-level-3",
        "azure-release-hardening-1",
        "azure-release-hardening-2",
        "azure-release-hardening-3",
        "github-azure-level-2"
      ]
    },
    {
      "id": "AZ-PIPE-029",
      "title": "Azure checkout avoids persistCredentials true",
      "category": "ci_cd",
      "assurance": "deterministic",
      "lifecycle": "stable",
      "weight": 2,
      "profiles": [
        "azure-level-1",
        "azure-level-2",
        "azure-level-3",
        "azure-release-hardening-1",
        "azure-release-hardening-2",
        "azure-release-hardening-3",
        "github-azure-level-2"
      ]
    },
    {
      "id": "AZ-PIPE-030",
      "title": "Azure pipelines use secure template extension posture",
      "category": "ci_cd",
      "assurance": "deterministic",
      "lifecycle": "stable",
      "weight": 1,
      "profiles": [
        "azure-level-2",
        "azure-level-3",
        "azure-release-hardening-2",
        "azure-release-hardening-3",
        "github-azure-level-2"
      ]
    },
    {
      "id": "AZ-SEC-031",
      "title": "Azure pipeline security scan signal detected",
      "category": "vulnerability_management",
      "assurance": "signal",
      "lifecycle": "stable",
      "weight": 1,
      "profiles": [
        "azure-level-1",
        "azure-level-2",
        "azure-release-hardening-1",
        "azure-release-hardening-2",
        "azure-release-hardening-3",
        "github-azure-level-2"
      ]
    },
    {
      "id": "AZ-SCA-032",
      "title": "Azure pipeline dependency audit or SCA signal detected",
      "category": "supply_chain",
      "assurance": "signal",
      "lifecycle": "stable",
      "weight": 1,
      "profiles": [
        "azure-level-1",
        "azure-level-2",
        "azure-release-hardening-1",
        "azure-release-hardening-2",
        "azure-release-hardening-3",
        "github-azure-level-2"
      ]
    },
    {
      "id": "AZ-SBOM-033",
      "title": "Azure pipeline SBOM generation signal detected",
      "category": "supply_chain",
      "assurance": "signal",
      "lifecycle": "stable",
      "weight": 1,
      "profiles": [
        "azure-level-1",
        "azure-level-2",
        "azure-release-hardening-1",
        "azure-release-hardening-2",
        "azure-release-hardening-3",
        "github-azure-level-2"
      ]
    },
    {
      "id": "AZ-PLAT-034",
      "title": "Azure Repos branch policy posture evidenced",
      "category": "platform",
      "assurance": "evidence-backed",
      "lifecycle": "stable",
      "weight": 3,
      "profiles": [
        "azure-level-3",
        "azure-release-hardening-1",
        "azure-release-hardening-2",
        "azure-release-hardening-3"
      ]
    },
    {
      "id": "AZ-PLAT-035",
      "title": "Azure pipeline governance posture evidenced",
      "category": "platform",
      "assurance": "evidence-backed",
      "lifecycle": "stable",
      "weight": 3,
      "profiles": [
        "azure-level-3",
        "azure-release-hardening-1",
        "azure-release-hardening-2",
        "azure-release-hardening-3"
      ]
    },
    {
      "id": "AZ-IDENT-036",
      "title": "Azure deployment identity federation posture",
      "category": "platform",
      "assurance": "evidence-backed",
      "lifecycle": "stable",
      "weight": 2,
      "profiles": [
        "azure-level-2",
        "azure-level-3",
        "azure-release-hardening-2",
        "azure-release-hardening-3",
        "github-azure-level-2"
      ]
    },
    {
      "id": "AZ-SCONN-056",
      "title": "Azure DevOps service connection authentication posture evidenced",
      "category": "platform",
      "assurance": "evidence-backed",
      "lifecycle": "stable",
      "weight": 3,
      "profiles": [
        "azure-level-3",
        "azure-release-hardening-3"
      ]
    },
    {
      "id": "AZ-WIFEV-057",
      "title": "Azure DevOps workload identity federation posture evidenced",
      "category": "platform",
      "assurance": "evidence-backed",
      "lifecycle": "stable",
      "weight": 2,
      "profiles": [
        "azure-level-3",
        "azure-release-hardening-3"
      ]
    },
    {
      "id": "AZ-ARTSBOM-058",
      "title": "Azure DevOps SBOM attested against a concrete release artifact digest",
      "category": "supply_chain",
      "assurance": "evidence-backed",
      "lifecycle": "stable",
      "weight": 2,
      "profiles": [
        "azure-level-3",
        "azure-release-hardening-3"
      ]
    },
    {
      "id": "AZ-ARTPRV-059",
      "title": "Azure DevOps provenance or attestation attested against a concrete release artifact digest",
      "category": "supply_chain",
      "assurance": "evidence-backed",
      "lifecycle": "stable",
      "weight": 2,
      "profiles": [
        "azure-level-3",
        "azure-release-hardening-3"
      ]
    },
    {
      "id": "AWS-CI-037",
      "title": "AWS CodeBuild buildspec or committed CodePipeline file exists",
      "category": "ci_cd",
      "assurance": "deterministic",
      "lifecycle": "stable",
      "weight": 2,
      "profiles": [
        "aws-level-1",
        "aws-level-2",
        "aws-level-3",
        "aws-release-hardening-1",
        "aws-release-hardening-2",
        "aws-release-hardening-3",
        "github-aws-level-2"
      ]
    },
    {
      "id": "AWS-SECRET-038",
      "title": "CodeBuild buildspec avoids inline secret anti-patterns and prefers managed secret sources",
      "category": "ci_cd",
      "assurance": "deterministic",
      "lifecycle": "stable",
      "weight": 3,
      "profiles": [
        "aws-level-1",
        "aws-level-2",
        "aws-level-3",
        "aws-release-hardening-1",
        "aws-release-hardening-2",
        "aws-release-hardening-3",
        "github-aws-level-2"
      ]
    },
    {
      "id": "AWS-SEC-039",
      "title": "Security scanning signal in CodeBuild buildspec",
      "category": "vulnerability_management",
      "assurance": "signal",
      "lifecycle": "stable",
      "weight": 1,
      "profiles": [
        "aws-level-1",
        "aws-level-2",
        "aws-release-hardening-1",
        "aws-release-hardening-2",
        "aws-release-hardening-3",
        "github-aws-level-2"
      ]
    },
    {
      "id": "AWS-SCA-040",
      "title": "Dependency audit or SCA signal in CodeBuild buildspec",
      "category": "supply_chain",
      "assurance": "signal",
      "lifecycle": "stable",
      "weight": 1,
      "profiles": [
        "aws-level-1",
        "aws-level-2",
        "aws-release-hardening-1",
        "aws-release-hardening-2",
        "aws-release-hardening-3",
        "github-aws-level-2"
      ]
    },
    {
      "id": "AWS-SBOM-041",
      "title": "SBOM generation signal in CodeBuild buildspec",
      "category": "supply_chain",
      "assurance": "signal",
      "lifecycle": "stable",
      "weight": 1,
      "profiles": [
        "aws-level-1",
        "aws-level-2",
        "aws-release-hardening-1",
        "aws-release-hardening-2",
        "aws-release-hardening-3",
        "github-aws-level-2"
      ]
    },
    {
      "id": "AWS-PIPE-042",
      "title": "Committed CodePipeline export under pipelines/aws/ with minimal useful structure",
      "category": "ci_cd",
      "assurance": "deterministic",
      "lifecycle": "stable",
      "weight": 2,
      "profiles": [
        "aws-level-2",
        "aws-level-3",
        "aws-release-hardening-2",
        "aws-release-hardening-3",
        "github-aws-level-2"
      ]
    },
    {
      "id": "AWS-PROV-043",
      "title": "Provenance or attestation signal in CodeBuild buildspec",
      "category": "supply_chain",
      "assurance": "signal",
      "lifecycle": "stable",
      "weight": 1,
      "profiles": [
        "aws-level-2",
        "aws-release-hardening-2",
        "aws-release-hardening-3",
        "github-aws-level-2"
      ]
    },
    {
      "id": "AWS-CP-044",
      "title": "CodePipeline promotion and artifact governance evidenced",
      "category": "platform",
      "assurance": "evidence-backed",
      "lifecycle": "stable",
      "weight": 3,
      "profiles": [
        "aws-level-3",
        "aws-release-hardening-1",
        "aws-release-hardening-2",
        "aws-release-hardening-3"
      ]
    },
    {
      "id": "AWS-CB-045",
      "title": "CodeBuild project posture evidenced",
      "category": "platform",
      "assurance": "evidence-backed",
      "lifecycle": "stable",
      "weight": 3,
      "profiles": [
        "aws-level-3",
        "aws-release-hardening-1",
        "aws-release-hardening-2",
        "aws-release-hardening-3"
      ]
    },
    {
      "id": "AWS-PIPEIAM-056",
      "title": "CodePipeline service role / IAM execution boundary evidenced",
      "category": "platform",
      "assurance": "evidence-backed",
      "lifecycle": "stable",
      "weight": 3,
      "profiles": [
        "aws-level-3",
        "aws-release-hardening-3"
      ]
    },
    {
      "id": "AWS-CBIDENT-057",
      "title": "CodeBuild project identity and credential boundary evidenced",
      "category": "platform",
      "assurance": "evidence-backed",
      "lifecycle": "stable",
      "weight": 3,
      "profiles": [
        "aws-level-3",
        "aws-release-hardening-3"
      ]
    },
    {
      "id": "AWS-SBOMART-058",
      "title": "SBOM attested against a concrete release artifact digest",
      "category": "supply_chain",
      "assurance": "evidence-backed",
      "lifecycle": "stable",
      "weight": 2,
      "profiles": [
        "aws-level-3",
        "aws-release-hardening-3"
      ]
    },
    {
      "id": "AWS-PROVART-059",
      "title": "Provenance or attestation attested against a concrete release artifact digest",
      "category": "supply_chain",
      "assurance": "evidence-backed",
      "lifecycle": "stable",
      "weight": 2,
      "profiles": [
        "aws-level-3",
        "aws-release-hardening-3"
      ]
    },
    {
      "id": "SEC-SECRETS-050",
      "title": "Secret scanning tool in CI",
      "category": "vulnerability_management",
      "assurance": "signal",
      "lifecycle": "stable",
      "weight": 2,
      "profiles": [
        "appsec-sast-sca-1",
        "cra-eu-ready-1",
        "cra-eu-reporting-1",
        "cra-eu-strict-1",
        "github-aws-level-2",
        "github-azure-level-2",
        "github-level-2",
        "osps-baseline-1",
        "osps-baseline-2026-1",
        "owasp-cicd-top10-1",
        "ssdf-baseline-1"
      ]
    },
    {
      "id": "SEC-GITIGNORE-051",
      "title": ".gitignore present with basic secret protection patterns",
      "category": "governance",
      "assurance": "deterministic",
      "lifecycle": "stable",
      "weight": 1,
      "profiles": [
        "appsec-sast-sca-1",
        "aws-level-2",
        "aws-level-3",
        "aws-release-hardening-1",
        "aws-release-hardening-2",
        "aws-release-hardening-3",
        "azure-level-2",
        "azure-level-3",
        "azure-release-hardening-1",
        "azure-release-hardening-2",
        "azure-release-hardening-3",
        "github-aws-level-2",
        "github-azure-level-2",
        "github-level-2",
        "github-level-3",
        "gitlab-release-hardening-1",
        "gitlab-release-hardening-2",
        "gitlab-release-hardening-3"
      ]
    },
    {
      "id": "SEC-PINLOCK-052",
      "title": "Dependency lockfile or pinned dependencies present",
      "category": "supply_chain",
      "assurance": "deterministic",
      "lifecycle": "stable",
      "weight": 2,
      "profiles": [
        "appsec-sast-sca-1",
        "aws-level-2",
        "aws-level-3",
        "aws-release-hardening-1",
        "aws-release-hardening-2",
        "aws-release-hardening-3",
        "azure-level-2",
        "azure-level-3",
        "azure-release-hardening-1",
        "azure-release-hardening-2",
        "azure-release-hardening-3",
        "cis-supply-chain-1",
        "github-aws-level-2",
        "github-azure-level-2",
        "github-level-2",
        "github-level-3",
        "gitlab-release-hardening-1",
        "gitlab-release-hardening-2",
        "gitlab-release-hardening-3",
        "owasp-cicd-top10-1",
        "s2c2f-l1-1",
        "s2c2f-l2-1",
        "s2c2f-l3-1"
      ]
    },
    {
      "id": "GH-MERGEQ-053",
      "title": "GitHub merge queue or merge_group trigger posture",
      "category": "ci_cd",
      "assurance": "signal",
      "lifecycle": "stable",
      "weight": 1,
      "profiles": [
        "github-aws-level-2",
        "github-azure-level-2",
        "github-level-2",
        "github-level-3",
        "github-release-hardening-3",
        "owasp-cicd-top10-1"
      ]
    },
    {
      "id": "GOV-EVIDFRESH-054",
      "title": "Collected evidence under .oss-policy-kit/evidence is not stale",
      "category": "governance",
      "assurance": "deterministic",
      "lifecycle": "stable",
      "weight": 2,
      "profiles": [
        "aws-level-3",
        "aws-release-hardening-3",
        "azure-level-3",
        "azure-release-hardening-2",
        "azure-release-hardening-3",
        "container-baseline-1",
        "cra-eu-reporting-1",
        "cra-eu-strict-1",
        "github-level-3",
        "github-release-hardening-1",
        "github-release-hardening-2",
        "github-release-hardening-3",
        "gitlab-level-3",
        "gitlab-release-hardening-2",
        "gitlab-release-hardening-3",
        "iac-bicep-baseline-1",
        "iac-cfn-baseline-1",
        "iac-pulumi-baseline-1",
        "iac-terraform-baseline-1",
        "kubernetes-baseline-1",
        "ssdf-baseline-1",
        "webhook-security-1",
        "webhook-security-2"
      ]
    },
    {
      "id": "CI-WFCALLSHA-055",
      "title": "Reusable workflow calls pinned to immutable commit SHAs",
      "category": "ci_cd",
      "assurance": "deterministic",
      "lifecycle": "stable",
      "weight": 3,
      "profiles": [
        "appsec-sast-sca-1",
        "cis-supply-chain-1",
        "github-level-3",
        "github-release-hardening-3",
        "owasp-cicd-top10-1",
        "s2c2f-l2-1",
        "s2c2f-l3-1",
        "slsa-build-l2-1",
        "ssdf-baseline-1"
      ]
    },
    {
      "id": "DEP-UPDATE-001",
      "title": "Automated dependency update tool configured (Dependabot or Renovate)",
      "category": "supply_chain",
      "assurance": "deterministic",
      "lifecycle": "stable",
      "weight": 2,
      "profiles": [
        "appsec-llm-ssdf-218a-1",
        "appsec-sast-sca-1",
        "aws-level-2",
        "aws-level-3",
        "aws-release-hardening-2",
        "aws-release-hardening-3",
        "azure-level-2",
        "azure-level-3",
        "azure-release-hardening-2",
        "azure-release-hardening-3",
        "cis-supply-chain-1",
        "cra-eu-ready-1",
        "cra-eu-reporting-1",
        "cra-eu-strict-1",
        "github-aws-level-2",
        "github-azure-level-2",
        "github-level-2",
        "github-level-3",
        "github-release-hardening-2",
        "github-release-hardening-3",
        "gitlab-level-1",
        "gitlab-level-2",
        "gitlab-level-3",
        "gitlab-release-hardening-1",
        "gitlab-release-hardening-2",
        "gitlab-release-hardening-3",
        "osps-baseline-1",
        "osps-baseline-2026-1",
        "s2c2f-l1-1",
        "s2c2f-l2-1",
        "s2c2f-l3-1",
        "ssdf-baseline-1"
      ]
    },
    {
      "id": "OSS-SCORECARD-001",
      "title": "OpenSSF Scorecard score meets minimum threshold",
      "category": "vulnerability_management",
      "assurance": "signal",
      "lifecycle": "stable",
      "weight": 1,
      "profiles": [
        "github-level-2",
        "github-level-3",
        "github-release-hardening-2",
        "github-release-hardening-3",
        "s2c2f-l1-1",
        "s2c2f-l2-1",
        "s2c2f-l3-1"
      ]
    },
    {
      "id": "CONT-IMAGE-001",
      "title": "Dockerfile base images pinned to immutable digest",
      "category": "supply_chain",
      "assurance": "deterministic",
      "lifecycle": "stable",
      "weight": 2,
      "profiles": [
        "aws-level-2",
        "aws-level-3",
        "aws-release-hardening-2",
        "aws-release-hardening-3",
        "azure-level-2",
        "azure-level-3",
        "azure-release-hardening-2",
        "azure-release-hardening-3",
        "container-baseline-1",
        "github-aws-level-2",
        "github-azure-level-2",
        "github-level-2",
        "github-level-3",
        "github-release-hardening-2",
        "github-release-hardening-3",
        "gitlab-release-hardening-2",
        "gitlab-release-hardening-3"
      ]
    },
    {
      "id": "CONT-IMAGE-002",
      "title": "Dockerfile declares non-root USER",
      "category": "ci_cd",
      "assurance": "deterministic",
      "lifecycle": "stable",
      "weight": 2,
      "profiles": [
        "aws-level-2",
        "aws-level-3",
        "aws-release-hardening-2",
        "aws-release-hardening-3",
        "azure-level-2",
        "azure-level-3",
        "azure-release-hardening-2",
        "azure-release-hardening-3",
        "container-baseline-1",
        "github-aws-level-2",
        "github-azure-level-2",
        "github-level-2",
        "github-level-3",
        "github-release-hardening-2",
        "github-release-hardening-3",
        "gitlab-release-hardening-2",
        "gitlab-release-hardening-3"
      ]
    },
    {
      "id": "CONT-IMAGE-003",
      "title": "Container image scanning signal in CI",
      "category": "vulnerability_management",
      "assurance": "signal",
      "lifecycle": "stable",
      "weight": 1,
      "profiles": [
        "aws-level-2",
        "aws-level-3",
        "aws-release-hardening-2",
        "aws-release-hardening-3",
        "azure-level-2",
        "azure-level-3",
        "azure-release-hardening-2",
        "azure-release-hardening-3",
        "container-baseline-1",
        "github-aws-level-2",
        "github-azure-level-2",
        "github-level-2",
        "github-level-3",
        "github-release-hardening-2",
        "github-release-hardening-3",
        "gitlab-release-hardening-2",
        "gitlab-release-hardening-3"
      ]
    },
    {
      "id": "ORG-MFA-001",
      "title": "Organization MFA enforcement posture evidenced",
      "category": "platform",
      "assurance": "evidence-backed",
      "lifecycle": "stable",
      "weight": 3,
      "profiles": [
        "aws-level-3",
        "aws-release-hardening-3",
        "azure-level-3",
        "azure-release-hardening-3",
        "cis-supply-chain-1",
        "cra-eu-strict-1",
        "github-level-3",
        "github-release-hardening-3",
        "gitlab-level-3",
        "gitlab-release-hardening-3",
        "osps-baseline-1",
        "osps-baseline-2026-1",
        "owasp-cicd-top10-1",
        "ssdf-baseline-1"
      ]
    },
    {
      "id": "BUILD-SBOM-QUAL-003",
      "title": "SBOM format validity and completeness signal",
      "category": "supply_chain",
      "assurance": "signal",
      "lifecycle": "stable",
      "weight": 2,
      "profiles": [
        "aws-level-3",
        "aws-release-hardening-3",
        "azure-level-3",
        "azure-release-hardening-3",
        "cis-supply-chain-1",
        "cra-eu-ready-1",
        "cra-eu-reporting-1",
        "cra-eu-strict-1",
        "github-level-3",
        "github-release-hardening-3",
        "gitlab-level-1",
        "gitlab-level-2",
        "gitlab-level-3",
        "gitlab-release-hardening-1",
        "gitlab-release-hardening-2",
        "gitlab-release-hardening-3",
        "osps-baseline-1",
        "osps-baseline-2026-1",
        "owasp-cicd-top10-1",
        "s2c2f-l1-1",
        "s2c2f-l2-1",
        "s2c2f-l3-1",
        "slsa-build-l2-1",
        "ssdf-baseline-1"
      ]
    },
    {
      "id": "AUDIT-STREAM-060",
      "title": "Audit log streaming to centralized SIEM/object store",
      "category": "governance",
      "assurance": "evidence-backed",
      "lifecycle": "stable",
      "weight": 2,
      "profiles": [
        "aws-level-3",
        "aws-release-hardening-3",
        "azure-level-3",
        "azure-release-hardening-3",
        "cra-eu-ready-1",
        "cra-eu-reporting-1",
        "cra-eu-strict-1",
        "github-level-3",
        "github-release-hardening-3",
        "gitlab-level-3",
        "gitlab-release-hardening-3",
        "owasp-cicd-top10-1",
        "s2c2f-l3-1",
        "ssdf-baseline-1"
      ]
    },
    {
      "id": "PROV-VERIFY-061",
      "title": "Build provenance attestation is verifiable (sigstore / Artifact Attestations)",
      "category": "supply_chain",
      "assurance": "evidence-backed",
      "lifecycle": "stable",
      "weight": 3,
      "profiles": [
        "aws-level-3",
        "aws-release-hardening-3",
        "azure-level-3",
        "azure-release-hardening-3",
        "cis-supply-chain-1",
        "cra-eu-ready-1",
        "cra-eu-strict-1",
        "github-level-3",
        "github-release-hardening-3",
        "gitlab-level-3",
        "gitlab-release-hardening-3",
        "oss-publish-readiness-1",
        "owasp-cicd-top10-1",
        "s2c2f-l3-1",
        "slsa-build-l2-1",
        "ssdf-baseline-1"
      ]
    },
    {
      "id": "GH-RUNNER-062",
      "title": "Self-hosted runners are ephemeral and restricted from PR-triggered workflows",
      "category": "ci_cd",
      "assurance": "signal",
      "lifecycle": "stable",
      "weight": 3,
      "profiles": [
        "cis-supply-chain-1",
        "github-level-2",
        "github-level-3",
        "github-release-hardening-2",
        "github-release-hardening-3",
        "owasp-cicd-top10-1",
        "slsa-build-l2-1"
      ]
    },
    {
      "id": "RELEASE-ARCHIVE-063",
      "title": "Release artifacts have an explicit archival/retention policy",
      "category": "release",
      "assurance": "signal",
      "lifecycle": "stable",
      "weight": 2,
      "profiles": [
        "aws-release-hardening-3",
        "azure-release-hardening-3",
        "cis-supply-chain-1",
        "cra-eu-ready-1",
        "cra-eu-strict-1",
        "github-release-hardening-3",
        "gitlab-release-hardening-3"
      ]
    },
    {
      "id": "GH-IMMUTREL-070",
      "title": "GitHub immutable releases enabled / release attestation evidenced",
      "category": "supply_chain",
      "assurance": "evidence-backed",
      "lifecycle": "experimental",
      "weight": 2,
      "profiles": [
        "github-release-hardening-2",
        "github-release-hardening-3"
      ]
    },
    {
      "id": "ORG-ACTPOL-071",
      "title": "Organization-level Actions policy (block + SHA-pinning) evidenced",
      "category": "platform",
      "assurance": "evidence-backed",
      "lifecycle": "experimental",
      "weight": 2,
      "profiles": [
        "github-release-hardening-2",
        "github-release-hardening-3"
      ]
    },
    {
      "id": "SAST-SEMGREP-064",
      "title": "SAST scan evidence (Semgrep) is present and current",
      "category": "ci_cd",
      "assurance": "evidence-backed",
      "lifecycle": "stable",
      "weight": 3,
      "profiles": [
        "appsec-sast-sca-1"
      ]
    },
    {
      "id": "GOV-DISC-065",
      "title": "Disclosure channel SLA documented (CRA reporting readiness)",
      "category": "governance",
      "assurance": "evidence-backed",
      "lifecycle": "stable",
      "weight": 2,
      "profiles": [
        "cra-eu-ai-act-art11-1",
        "cra-eu-ready-2-1",
        "cra-eu-reporting-1",
        "gitlab-level-3",
        "gitlab-release-hardening-3"
      ]
    },
    {
      "id": "SAST-ZIZMOR-066",
      "title": "zizmor SARIF findings (GitHub Actions security AST analysis)",
      "category": "ci_cd",
      "assurance": "evidence-backed",
      "lifecycle": "experimental",
      "weight": 2,
      "profiles": [
        "appsec-sast-sca-1"
      ]
    },
    {
      "id": "SAST-POUTINE-067",
      "title": "poutine SARIF findings (GitHub Actions / GitLab CI pipeline scanner)",
      "category": "ci_cd",
      "assurance": "evidence-backed",
      "lifecycle": "experimental",
      "weight": 2,
      "profiles": [
        "appsec-sast-sca-1",
        "gitlab-release-hardening-3"
      ]
    },
    {
      "id": "SAST-OSV-068",
      "title": "OSV-Scanner v2 SARIF findings (reachability-aware SCA)",
      "category": "supply_chain",
      "assurance": "evidence-backed",
      "lifecycle": "experimental",
      "weight": 3,
      "profiles": [
        "appsec-llm-ssdf-218a-1",
        "appsec-sast-sca-1",
        "cra-eu-ai-act-art11-1",
        "cra-eu-ready-2-1",
        "s2c2f-l2-1",
        "s2c2f-l3-1"
      ]
    },
    {
      "id": "SAST-GITLEAKS-069",
      "title": "Gitleaks SARIF findings (secret leak detection)",
      "category": "secure_development",
      "assurance": "evidence-backed",
      "lifecycle": "experimental",
      "weight": 3,
      "profiles": [
        "appsec-sast-sca-1",
        "s2c2f-l3-1"
      ]
    },
    {
      "id": "GL-PIPE-001",
      "title": "GitLab CI pipeline files present and parseable",
      "category": "ci_cd",
      "assurance": "deterministic",
      "lifecycle": "experimental",
      "weight": 1,
      "profiles": [
        "gitlab-level-1",
        "gitlab-level-2",
        "gitlab-level-3",
        "gitlab-release-hardening-1",
        "gitlab-release-hardening-2",
        "gitlab-release-hardening-3"
      ]
    },
    {
      "id": "GL-PIPE-002",
      "title": "GitLab CI image references pinned to a tag or digest",
      "category": "ci_cd",
      "assurance": "signal",
      "lifecycle": "experimental",
      "weight": 2,
      "profiles": [
        "gitlab-level-1",
        "gitlab-level-2",
        "gitlab-level-3",
        "gitlab-release-hardening-1",
        "gitlab-release-hardening-2",
        "gitlab-release-hardening-3"
      ]
    },
    {
      "id": "GL-PIPE-003",
      "title": "GitLab CI scripts do not pipe network downloads to a shell",
      "category": "ci_cd",
      "assurance": "signal",
      "lifecycle": "experimental",
      "weight": 3,
      "profiles": [
        "gitlab-level-1",
        "gitlab-level-2",
        "gitlab-level-3",
        "gitlab-release-hardening-1",
        "gitlab-release-hardening-2",
        "gitlab-release-hardening-3"
      ]
    },
    {
      "id": "GL-PIPE-004",
      "title": "GitLab CI jobs do not declare broad `inherit: secrets: true`",
      "category": "ci_cd",
      "assurance": "deterministic",
      "lifecycle": "experimental",
      "weight": 2,
      "profiles": [
        "gitlab-level-1",
        "gitlab-level-2",
        "gitlab-level-3",
        "gitlab-release-hardening-1",
        "gitlab-release-hardening-2",
        "gitlab-release-hardening-3"
      ]
    },
    {
      "id": "GL-PIPE-005",
      "title": "GitLab CI `include:` does not reference unpinned remote URLs",
      "category": "ci_cd",
      "assurance": "signal",
      "lifecycle": "experimental",
      "weight": 2,
      "profiles": [
        "gitlab-level-1",
        "gitlab-level-2",
        "gitlab-level-3",
        "gitlab-release-hardening-1",
        "gitlab-release-hardening-2",
        "gitlab-release-hardening-3"
      ]
    },
    {
      "id": "GL-PIPE-006",
      "title": "GitLab CI jobs use trigger restrictions (`rules:` / `only:` / `except:`)",
      "category": "ci_cd",
      "assurance": "signal",
      "lifecycle": "experimental",
      "weight": 1,
      "profiles": [
        "gitlab-level-1",
        "gitlab-level-2",
        "gitlab-level-3",
        "gitlab-release-hardening-1",
        "gitlab-release-hardening-2",
        "gitlab-release-hardening-3"
      ]
    },
    {
      "id": "IAC-TF-001",
      "title": "Terraform - object storage configured for public access",
      "category": "iac",
      "assurance": "evidence-backed",
      "lifecycle": "experimental",
      "weight": 3,
      "profiles": [
        "iac-terraform-baseline-1"
      ]
    },
    {
      "id": "IAC-TF-002",
      "title": "Terraform - security group exposes management port to 0.0.0.0/0",
      "category": "iac",
      "assurance": "evidence-backed",
      "lifecycle": "experimental",
      "weight": 3,
      "profiles": [
        "iac-terraform-baseline-1"
      ]
    },
    {
      "id": "IAC-TF-003",
      "title": "Terraform - IAM grants AdministratorAccess or Action=* + Resource=*",
      "category": "iac",
      "assurance": "evidence-backed",
      "lifecycle": "experimental",
      "weight": 3,
      "profiles": [
        "iac-terraform-baseline-1"
      ]
    },
    {
      "id": "IAC-TF-004",
      "title": "Terraform - storage / RDS / EBS resource without encryption-at-rest",
      "category": "iac",
      "assurance": "evidence-backed",
      "lifecycle": "experimental",
      "weight": 2,
      "profiles": [
        "iac-terraform-baseline-1"
      ]
    },
    {
      "id": "IAC-TF-005",
      "title": "Terraform - audit / access logging disabled on sensitive resources",
      "category": "iac",
      "assurance": "evidence-backed",
      "lifecycle": "experimental",
      "weight": 2,
      "profiles": [
        "iac-terraform-baseline-1"
      ]
    },
    {
      "id": "IAC-TF-006",
      "title": "Terraform - default VPC / subnet / security group used in declarations",
      "category": "iac",
      "assurance": "evidence-backed",
      "lifecycle": "experimental",
      "weight": 2,
      "profiles": [
        "iac-terraform-baseline-1"
      ]
    },
    {
      "id": "IAC-TF-007",
      "title": "Terraform - workload assigned a public IP without explicit intent",
      "category": "iac",
      "assurance": "evidence-backed",
      "lifecycle": "experimental",
      "weight": 2,
      "profiles": [
        "iac-terraform-baseline-1"
      ]
    },
    {
      "id": "IAC-TF-008",
      "title": "Terraform - AWS resources without owner / cost_center tags",
      "category": "iac",
      "assurance": "evidence-backed",
      "lifecycle": "experimental",
      "weight": 1,
      "profiles": [
        "iac-terraform-baseline-1"
      ]
    },
    {
      "id": "IAC-TF-009",
      "title": "Terraform - provider versions not pinned in required_providers",
      "category": "iac",
      "assurance": "evidence-backed",
      "lifecycle": "experimental",
      "weight": 1,
      "profiles": [
        "iac-terraform-baseline-1"
      ]
    },
    {
      "id": "IAC-TF-010",
      "title": "Terraform - local backend used (no remote + encryption + locking)",
      "category": "iac",
      "assurance": "evidence-backed",
      "lifecycle": "experimental",
      "weight": 1,
      "profiles": [
        "iac-terraform-baseline-1"
      ]
    },
    {
      "id": "IAC-TF-011",
      "title": "Terraform - production-naming data store missing lifecycle.prevent_destroy",
      "category": "iac",
      "assurance": "evidence-backed",
      "lifecycle": "experimental",
      "weight": 2,
      "profiles": [
        "iac-terraform-baseline-1"
      ]
    },
    {
      "id": "IAC-TF-012",
      "title": "Terraform - data.aws_iam_policy_document uses wildcard principal '*'",
      "category": "iac",
      "assurance": "evidence-backed",
      "lifecycle": "experimental",
      "weight": 1,
      "profiles": [
        "iac-terraform-baseline-1"
      ]
    },
    {
      "id": "SEC-FUZZ-001",
      "title": "Fuzzing presence (OSS-Fuzz / cifuzz / atheris / Scorecard Fuzzing)",
      "category": "vulnerability_management",
      "assurance": "signal",
      "lifecycle": "experimental",
      "weight": 2,
      "profiles": [
        "aws-level-3",
        "aws-release-hardening-3",
        "azure-level-3",
        "azure-release-hardening-3",
        "github-level-3",
        "github-release-hardening-3",
        "gitlab-level-3",
        "gitlab-release-hardening-3"
      ]
    },
    {
      "id": "CONT-RUNTIME-001",
      "title": "Container - multi-stage Dockerfile build",
      "category": "container",
      "assurance": "signal",
      "lifecycle": "experimental",
      "weight": 2,
      "profiles": [
        "container-baseline-1"
      ]
    },
    {
      "id": "CONT-RUNTIME-002",
      "title": "Container - Dockerfile HEALTHCHECK declared",
      "category": "container",
      "assurance": "signal",
      "lifecycle": "experimental",
      "weight": 1,
      "profiles": [
        "container-baseline-1"
      ]
    },
    {
      "id": "CONT-RUNTIME-003",
      "title": "Container - no curl|bash / wget|sh patterns in Dockerfile RUN",
      "category": "container",
      "assurance": "signal",
      "lifecycle": "experimental",
      "weight": 2,
      "profiles": [
        "container-baseline-1"
      ]
    },
    {
      "id": "CONT-RUNTIME-004",
      "title": "Container - .dockerignore present",
      "category": "container",
      "assurance": "signal",
      "lifecycle": "experimental",
      "weight": 1,
      "profiles": [
        "container-baseline-1"
      ]
    },
    {
      "id": "CONT-RUNTIME-005",
      "title": "Container - apt-get hygiene (--no-install-recommends or cache cleanup)",
      "category": "container",
      "assurance": "signal",
      "lifecycle": "experimental",
      "weight": 2,
      "profiles": [
        "container-baseline-1"
      ]
    },
    {
      "id": "CONT-RUNTIME-006",
      "title": "Container - OS package versions pinned in apt/apk install",
      "category": "container",
      "assurance": "signal",
      "lifecycle": "experimental",
      "weight": 1,
      "profiles": [
        "container-baseline-1"
      ]
    },
    {
      "id": "CONT-SIGN-001",
      "title": "Container - image signed via cosign or GitHub artifact attestations",
      "category": "supply_chain",
      "assurance": "signal",
      "lifecycle": "experimental",
      "weight": 3,
      "profiles": [
        "container-baseline-1"
      ]
    },
    {
      "id": "K8S-PSS-001",
      "title": "Kubernetes - privileged container detected",
      "category": "kubernetes",
      "assurance": "evidence-backed",
      "lifecycle": "experimental",
      "weight": 3,
      "profiles": [
        "kubernetes-baseline-1"
      ]
    },
    {
      "id": "K8S-PSS-002",
      "title": "Kubernetes - pod uses hostPID=true",
      "category": "kubernetes",
      "assurance": "evidence-backed",
      "lifecycle": "experimental",
      "weight": 3,
      "profiles": [
        "kubernetes-baseline-1"
      ]
    },
    {
      "id": "K8S-PSS-003",
      "title": "Kubernetes - pod uses hostNetwork=true",
      "category": "kubernetes",
      "assurance": "evidence-backed",
      "lifecycle": "experimental",
      "weight": 3,
      "profiles": [
        "kubernetes-baseline-1"
      ]
    },
    {
      "id": "K8S-PSS-004",
      "title": "Kubernetes - pod mounts hostPath volume",
      "category": "kubernetes",
      "assurance": "evidence-backed",
      "lifecycle": "experimental",
      "weight": 3,
      "profiles": [
        "kubernetes-baseline-1"
      ]
    },
    {
      "id": "K8S-PSS-005",
      "title": "Kubernetes - container adds Linux capabilities",
      "category": "kubernetes",
      "assurance": "evidence-backed",
      "lifecycle": "experimental",
      "weight": 2,
      "profiles": [
        "kubernetes-baseline-1"
      ]
    },
    {
      "id": "K8S-PSS-006",
      "title": "Kubernetes - container may run as root (runAsNonRoot/runAsUser not pinned)",
      "category": "kubernetes",
      "assurance": "evidence-backed",
      "lifecycle": "experimental",
      "weight": 3,
      "profiles": [
        "kubernetes-baseline-1"
      ]
    },
    {
      "id": "K8S-PSS-007",
      "title": "Kubernetes - allowPrivilegeEscalation not set to false",
      "category": "kubernetes",
      "assurance": "evidence-backed",
      "lifecycle": "experimental",
      "weight": 2,
      "profiles": [
        "kubernetes-baseline-1"
      ]
    },
    {
      "id": "K8S-PSS-008",
      "title": "Kubernetes - readOnlyRootFilesystem not true",
      "category": "kubernetes",
      "assurance": "evidence-backed",
      "lifecycle": "experimental",
      "weight": 2,
      "profiles": [
        "kubernetes-baseline-1"
      ]
    },
    {
      "id": "K8S-PSS-009",
      "title": "Kubernetes - automountServiceAccountToken not pinned",
      "category": "kubernetes",
      "assurance": "evidence-backed",
      "lifecycle": "experimental",
      "weight": 1,
      "profiles": [
        "kubernetes-baseline-1"
      ]
    },
    {
      "id": "K8S-PSS-010",
      "title": "Kubernetes - container image uses latest / unpinned tag",
      "category": "kubernetes",
      "assurance": "evidence-backed",
      "lifecycle": "experimental",
      "weight": 2,
      "profiles": [
        "kubernetes-baseline-1"
      ]
    },
    {
      "id": "K8S-RBAC-001",
      "title": "Kubernetes - Role / ClusterRole grants wildcard verb '*'",
      "category": "kubernetes",
      "assurance": "evidence-backed",
      "lifecycle": "experimental",
      "weight": 3,
      "profiles": [
        "kubernetes-baseline-1"
      ]
    },
    {
      "id": "K8S-RBAC-002",
      "title": "Kubernetes - RoleBinding / ClusterRoleBinding binds to cluster-admin",
      "category": "kubernetes",
      "assurance": "evidence-backed",
      "lifecycle": "experimental",
      "weight": 3,
      "profiles": [
        "kubernetes-baseline-1"
      ]
    },
    {
      "id": "K8S-RBAC-003",
      "title": "Kubernetes - workload uses default ServiceAccount in default namespace",
      "category": "kubernetes",
      "assurance": "evidence-backed",
      "lifecycle": "experimental",
      "weight": 1,
      "profiles": [
        "kubernetes-baseline-1"
      ]
    },
    {
      "id": "K8S-RBAC-004",
      "title": "Kubernetes - ClusterRole grants wildcard resource '*'",
      "category": "kubernetes",
      "assurance": "evidence-backed",
      "lifecycle": "experimental",
      "weight": 2,
      "profiles": [
        "kubernetes-baseline-1"
      ]
    },
    {
      "id": "K8S-RBAC-005",
      "title": "Kubernetes - Role / ClusterRole grants broad read on secrets",
      "category": "kubernetes",
      "assurance": "evidence-backed",
      "lifecycle": "experimental",
      "weight": 3,
      "profiles": [
        "kubernetes-baseline-1"
      ]
    },
    {
      "id": "K8S-NETPOL-001",
      "title": "Kubernetes - namespace with workloads but no NetworkPolicy",
      "category": "kubernetes",
      "assurance": "evidence-backed",
      "lifecycle": "experimental",
      "weight": 2,
      "profiles": [
        "kubernetes-baseline-1"
      ]
    },
    {
      "id": "IAC-CFN-001",
      "title": "CloudFormation - S3 bucket configured for public access",
      "category": "iac",
      "assurance": "evidence-backed",
      "lifecycle": "experimental",
      "weight": 3,
      "profiles": [
        "iac-cfn-baseline-1"
      ]
    },
    {
      "id": "IAC-CFN-002",
      "title": "CloudFormation - security group exposes management port to 0.0.0.0/0",
      "category": "iac",
      "assurance": "evidence-backed",
      "lifecycle": "experimental",
      "weight": 3,
      "profiles": [
        "iac-cfn-baseline-1"
      ]
    },
    {
      "id": "IAC-CFN-003",
      "title": "CloudFormation - IAM grants AdministratorAccess or Action=* + Resource=*",
      "category": "iac",
      "assurance": "evidence-backed",
      "lifecycle": "experimental",
      "weight": 3,
      "profiles": [
        "iac-cfn-baseline-1"
      ]
    },
    {
      "id": "IAC-CFN-004",
      "title": "CloudFormation - storage / RDS / EBS resource without encryption-at-rest",
      "category": "iac",
      "assurance": "evidence-backed",
      "lifecycle": "experimental",
      "weight": 2,
      "profiles": [
        "iac-cfn-baseline-1"
      ]
    },
    {
      "id": "IAC-CFN-005",
      "title": "CloudFormation - audit / access logging disabled on sensitive resources",
      "category": "iac",
      "assurance": "evidence-backed",
      "lifecycle": "experimental",
      "weight": 2,
      "profiles": [
        "iac-cfn-baseline-1"
      ]
    },
    {
      "id": "IAC-CFN-006",
      "title": "CloudFormation - workload assigned a public IP without explicit intent",
      "category": "iac",
      "assurance": "evidence-backed",
      "lifecycle": "experimental",
      "weight": 2,
      "profiles": [
        "iac-cfn-baseline-1"
      ]
    },
    {
      "id": "IAC-PUL-001",
      "title": "Pulumi - object storage configured for public access",
      "category": "iac",
      "assurance": "evidence-backed",
      "lifecycle": "experimental",
      "weight": 3,
      "profiles": [
        "iac-pulumi-baseline-1"
      ]
    },
    {
      "id": "IAC-PUL-002",
      "title": "Pulumi - security group exposes management port to 0.0.0.0/0",
      "category": "iac",
      "assurance": "evidence-backed",
      "lifecycle": "experimental",
      "weight": 3,
      "profiles": [
        "iac-pulumi-baseline-1"
      ]
    },
    {
      "id": "IAC-PUL-003",
      "title": "Pulumi - IAM grants AdministratorAccess or Action=* + Resource=*",
      "category": "iac",
      "assurance": "evidence-backed",
      "lifecycle": "experimental",
      "weight": 3,
      "profiles": [
        "iac-pulumi-baseline-1"
      ]
    },
    {
      "id": "IAC-PUL-004",
      "title": "Pulumi - storage / RDS / EBS resource without encryption-at-rest",
      "category": "iac",
      "assurance": "evidence-backed",
      "lifecycle": "experimental",
      "weight": 2,
      "profiles": [
        "iac-pulumi-baseline-1"
      ]
    },
    {
      "id": "IAC-PUL-005",
      "title": "Pulumi - default VPC / subnet / security group used in declarations",
      "category": "iac",
      "assurance": "evidence-backed",
      "lifecycle": "experimental",
      "weight": 2,
      "profiles": [
        "iac-pulumi-baseline-1"
      ]
    },
    {
      "id": "IAC-PUL-006",
      "title": "Pulumi - workload assigned a public IP without explicit intent",
      "category": "iac",
      "assurance": "evidence-backed",
      "lifecycle": "experimental",
      "weight": 2,
      "profiles": [
        "iac-pulumi-baseline-1"
      ]
    },
    {
      "id": "IAC-BICEP-001",
      "title": "Bicep - storage account configured for public access",
      "category": "iac",
      "assurance": "evidence-backed",
      "lifecycle": "experimental",
      "weight": 3,
      "profiles": [
        "iac-bicep-baseline-1"
      ]
    },
    {
      "id": "IAC-BICEP-002",
      "title": "Bicep - NSG rule allows management port inbound from '*'",
      "category": "iac",
      "assurance": "evidence-backed",
      "lifecycle": "experimental",
      "weight": 3,
      "profiles": [
        "iac-bicep-baseline-1"
      ]
    },
    {
      "id": "IAC-BICEP-003",
      "title": "Bicep - role assignment grants Owner / Contributor / User Access Admin",
      "category": "iac",
      "assurance": "evidence-backed",
      "lifecycle": "experimental",
      "weight": 3,
      "profiles": [
        "iac-bicep-baseline-1"
      ]
    },
    {
      "id": "IAC-BICEP-004",
      "title": "Bicep - storage / SQL / disk resource without encryption-at-rest",
      "category": "iac",
      "assurance": "evidence-backed",
      "lifecycle": "experimental",
      "weight": 2,
      "profiles": [
        "iac-bicep-baseline-1"
      ]
    },
    {
      "id": "IAC-BICEP-005",
      "title": "Bicep - sensitive resource has no diagnosticSettings paired",
      "category": "iac",
      "assurance": "evidence-backed",
      "lifecycle": "experimental",
      "weight": 1,
      "profiles": [
        "iac-bicep-baseline-1"
      ]
    },
    {
      "id": "IAC-BICEP-006",
      "title": "Bicep - direct public IP declared without documented intent",
      "category": "iac",
      "assurance": "evidence-backed",
      "lifecycle": "experimental",
      "weight": 2,
      "profiles": [
        "iac-bicep-baseline-1"
      ]
    },
    {
      "id": "SEC-WEBHOOK-001",
      "title": "Webhook receiver verifies inbound signature",
      "category": "secure_development",
      "assurance": "signal",
      "lifecycle": "experimental",
      "weight": 3,
      "profiles": [
        "webhook-security-1",
        "webhook-security-2"
      ]
    },
    {
      "id": "SEC-WEBHOOK-002",
      "title": "Webhook receiver implements replay defense (timestamp / nonce / idempotency)",
      "category": "secure_development",
      "assurance": "signal",
      "lifecycle": "experimental",
      "weight": 2,
      "profiles": [
        "webhook-security-1",
        "webhook-security-2"
      ]
    },
    {
      "id": "GH-EGRESS-HRN-001",
      "title": "GitHub Actions workflows declare Harden-Runner egress controls",
      "category": "ci_cd",
      "assurance": "signal",
      "lifecycle": "experimental",
      "weight": 2,
      "profiles": []
    },
    {
      "id": "SEC-WEBHOOK-HMAC-001",
      "title": "Webhook receiver invokes an HMAC verification helper",
      "category": "secure_development",
      "assurance": "signal",
      "lifecycle": "experimental",
      "weight": 3,
      "profiles": [
        "webhook-security-2"
      ]
    },
    {
      "id": "SEC-WEBHOOK-TIMING-002",
      "title": "Webhook signature comparison uses a timing-safe primitive",
      "category": "secure_development",
      "assurance": "signal",
      "lifecycle": "experimental",
      "weight": 2,
      "profiles": [
        "webhook-security-2"
      ]
    },
    {
      "id": "SEC-WEBHOOK-REPLAY-003",
      "title": "Webhook receiver enforces a timestamp tolerance or nonce window",
      "category": "secure_development",
      "assurance": "signal",
      "lifecycle": "experimental",
      "weight": 2,
      "profiles": [
        "webhook-security-2"
      ]
    },
    {
      "id": "SEC-WEBHOOK-BODY-004",
      "title": "Webhook receiver caps request-body size at the framework or proxy layer",
      "category": "secure_development",
      "assurance": "signal",
      "lifecycle": "experimental",
      "weight": 1,
      "profiles": [
        "webhook-security-2"
      ]
    },
    {
      "id": "SEC-WEBHOOK-IDEMP-005",
      "title": "Webhook receiver extracts an idempotency key and dedupes per delivery",
      "category": "secure_development",
      "assurance": "signal",
      "lifecycle": "experimental",
      "weight": 2,
      "profiles": [
        "webhook-security-2"
      ]
    },
    {
      "id": "SEC-WEBHOOK-ROTATE-006",
      "title": "Webhook secret sourced from env/vault and supports rotation window",
      "category": "secure_development",
      "assurance": "signal",
      "lifecycle": "experimental",
      "weight": 2,
      "profiles": [
        "webhook-security-2"
      ]
    },
    {
      "id": "PUBLISH-OIDC-001",
      "title": "Publish workflow declares OIDC id-token permission",
      "category": "ci_cd",
      "assurance": "signal",
      "lifecycle": "experimental",
      "weight": 3,
      "profiles": [
        "oss-publish-readiness-1"
      ]
    },
    {
      "id": "PUBLISH-OIDC-002",
      "title": "PyPI / RubyGems / crates publish step omits long-lived password",
      "category": "ci_cd",
      "assurance": "signal",
      "lifecycle": "experimental",
      "weight": 2,
      "profiles": [
        "oss-publish-readiness-1"
      ]
    },
    {
      "id": "PUBLISH-OIDC-003",
      "title": "npm publish step uses --provenance (or registry-equivalent flag)",
      "category": "ci_cd",
      "assurance": "signal",
      "lifecycle": "experimental",
      "weight": 2,
      "profiles": [
        "oss-publish-readiness-1"
      ]
    },
    {
      "id": "SLSA-SRC-001",
      "title": "Version-controlled source (SLSA Source Track L1 baseline)",
      "category": "supply_chain",
      "assurance": "deterministic",
      "lifecycle": "experimental",
      "weight": 1,
      "profiles": [
        "slsa-source-l1-1",
        "slsa-source-l2-1"
      ]
    },
    {
      "id": "SLSA-SRC-002",
      "title": "Commit-signature enforcement signal detected (SLSA Source verified history)",
      "category": "supply_chain",
      "assurance": "signal",
      "lifecycle": "experimental",
      "weight": 2,
      "profiles": [
        "slsa-source-l1-1",
        "slsa-source-l2-1"
      ]
    },
    {
      "id": "SLSA-SRC-003",
      "title": "Branch protection present (SLSA Source protected branches)",
      "category": "supply_chain",
      "assurance": "signal",
      "lifecycle": "experimental",
      "weight": 2,
      "profiles": [
        "slsa-source-l1-1",
        "slsa-source-l2-1"
      ]
    },
    {
      "id": "SLSA-SRC-004",
      "title": "Two-party review required on protected branches (SLSA Source)",
      "category": "supply_chain",
      "assurance": "signal",
      "lifecycle": "experimental",
      "weight": 2,
      "profiles": [
        "slsa-source-l1-1",
        "slsa-source-l2-1"
      ]
    },
    {
      "id": "SLSA-SRC-005",
      "title": "Audit log of source-changing events (SLSA Source auditability)",
      "category": "supply_chain",
      "assurance": "signal",
      "lifecycle": "experimental",
      "weight": 2,
      "profiles": [
        "slsa-source-l1-1",
        "slsa-source-l2-1"
      ]
    },
    {
      "id": "GL-PIPE-007",
      "title": "GitLab CI workflow uses OIDC (id_tokens) for cloud / registry access",
      "category": "ci_cd",
      "assurance": "signal",
      "lifecycle": "experimental",
      "weight": 3,
      "profiles": [
        "gitlab-level-2",
        "gitlab-level-3",
        "gitlab-release-hardening-2",
        "gitlab-release-hardening-3"
      ]
    },
    {
      "id": "GL-PIPE-008",
      "title": "GitLab CI restricts self-hosted runner usage via tags",
      "category": "ci_cd",
      "assurance": "signal",
      "lifecycle": "experimental",
      "weight": 2,
      "profiles": [
        "gitlab-level-2",
        "gitlab-level-3",
        "gitlab-release-hardening-2",
        "gitlab-release-hardening-3"
      ]
    },
    {
      "id": "GL-PIPE-009",
      "title": "GitLab project documents audit-event streaming or external export",
      "category": "ci_cd",
      "assurance": "signal",
      "lifecycle": "experimental",
      "weight": 2,
      "profiles": [
        "gitlab-level-2",
        "gitlab-level-3",
        "gitlab-release-hardening-2",
        "gitlab-release-hardening-3"
      ]
    },
    {
      "id": "GL-PIPE-010",
      "title": "GitLab CI environment approval rules declared for protected envs",
      "category": "ci_cd",
      "assurance": "signal",
      "lifecycle": "experimental",
      "weight": 2,
      "profiles": [
        "gitlab-level-2",
        "gitlab-level-3",
        "gitlab-release-hardening-2",
        "gitlab-release-hardening-3"
      ]
    },
    {
      "id": "GL-PIPE-011",
      "title": "GitLab CI merge-request rules enforce code-review approvals",
      "category": "ci_cd",
      "assurance": "signal",
      "lifecycle": "experimental",
      "weight": 2,
      "profiles": [
        "gitlab-level-2",
        "gitlab-level-3",
        "gitlab-release-hardening-2",
        "gitlab-release-hardening-3"
      ]
    },
    {
      "id": "GL-PIPE-012",
      "title": "GitLab CI artifact retention or signed-release posture documented",
      "category": "ci_cd",
      "assurance": "signal",
      "lifecycle": "experimental",
      "weight": 1,
      "profiles": [
        "gitlab-level-2",
        "gitlab-level-3",
        "gitlab-release-hardening-2",
        "gitlab-release-hardening-3"
      ]
    },
    {
      "id": "AIBOM-PRESENT-001",
      "title": "AI Bill of Materials present in evidence directory",
      "category": "supply_chain",
      "assurance": "signal",
      "lifecycle": "experimental",
      "weight": 2,
      "profiles": [
        "appsec-llm-ssdf-218a-1",
        "cra-eu-ai-act-art11-1"
      ]
    },
    {
      "id": "LLM-218A-PO-001",
      "title": "AI Security Considerations section present in SECURITY.md or README",
      "category": "secure_development",
      "assurance": "signal",
      "lifecycle": "experimental",
      "weight": 2,
      "profiles": [
        "appsec-agentic-asi-1",
        "appsec-llm-ssdf-218a-1",
        "appsec-mcp-server-1",
        "cra-eu-ai-act-art11-1"
      ]
    },
    {
      "id": "LLM-218A-PO-002",
      "title": "Prompt / system-instruction registry directory present",
      "category": "secure_development",
      "assurance": "signal",
      "lifecycle": "experimental",
      "weight": 1,
      "profiles": [
        "appsec-llm-ssdf-218a-1"
      ]
    },
    {
      "id": "LLM-218A-PS-001",
      "title": "LLM release-integrity evidence file populated",
      "category": "secure_development",
      "assurance": "evidence-backed",
      "lifecycle": "experimental",
      "weight": 3,
      "profiles": [
        "appsec-llm-ssdf-218a-1",
        "cra-eu-ai-act-art11-1"
      ]
    },
    {
      "id": "LLM-218A-PS-002",
      "title": "Model versioning artifacts (semver tags or release matching model/*)",
      "category": "secure_development",
      "assurance": "signal",
      "lifecycle": "experimental",
      "weight": 1,
      "profiles": [
        "appsec-llm-ssdf-218a-1"
      ]
    },
    {
      "id": "LLM-218A-PW-001",
      "title": "LLM SDK dependencies declared (transformers / openai / anthropic / langchain)",
      "category": "secure_development",
      "assurance": "signal",
      "lifecycle": "experimental",
      "weight": 2,
      "profiles": [
        "appsec-llm-ssdf-218a-1"
      ]
    },
    {
      "id": "LLM-218A-PW-002",
      "title": "Prompt-injection or adversarial test file present",
      "category": "secure_development",
      "assurance": "signal",
      "lifecycle": "experimental",
      "weight": 2,
      "profiles": [
        "appsec-llm-ssdf-218a-1"
      ]
    },
    {
      "id": "LLM-218A-RV-001",
      "title": "Dependabot or Renovate config explicitly lists LLM SDKs",
      "category": "secure_development",
      "assurance": "signal",
      "lifecycle": "experimental",
      "weight": 1,
      "profiles": [
        "appsec-llm-ssdf-218a-1"
      ]
    },
    {
      "id": "LLM-AI-ACT-001",
      "title": "Intended purpose / users / limitations documented (EU AI Act Annex IV §1)",
      "category": "secure_development",
      "assurance": "signal",
      "lifecycle": "experimental",
      "weight": 2,
      "profiles": [
        "cra-eu-ai-act-art11-1"
      ]
    },
    {
      "id": "LLM-AI-ACT-002",
      "title": "Output filtering / content moderation pattern detected (EU AI Act Annex IV §3)",
      "category": "secure_development",
      "assurance": "signal",
      "lifecycle": "experimental",
      "weight": 2,
      "profiles": [
        "cra-eu-ai-act-art11-1"
      ]
    },
    {
      "id": "LLM-AI-ACT-003",
      "title": "Risk management documentation present (EU AI Act Annex IV §5)",
      "category": "secure_development",
      "assurance": "signal",
      "lifecycle": "experimental",
      "weight": 2,
      "profiles": [
        "cra-eu-ai-act-art11-1"
      ]
    },
    {
      "id": "WORM-POSTINSTALL-001",
      "title": "package.json postinstall script free of credential-harvest primitives (Shai-Hulud defense)",
      "category": "supply_chain",
      "assurance": "signal",
      "lifecycle": "experimental",
      "weight": 3,
      "profiles": [
        "oss-publish-readiness-1"
      ]
    },
    {
      "id": "WORM-LOCKFILE-DRIFT-001",
      "title": "package.json / pyproject.toml not modified more recently than lockfile (worm-rewrite signal)",
      "category": "supply_chain",
      "assurance": "signal",
      "lifecycle": "experimental",
      "weight": 2,
      "profiles": [
        "oss-publish-readiness-1"
      ]
    },
    {
      "id": "WORM-PUBLISH-SCOPE-001",
      "title": "Publish workflow restricted to main/release branches with explicit scope",
      "category": "ci_cd",
      "assurance": "signal",
      "lifecycle": "experimental",
      "weight": 2,
      "profiles": [
        "oss-publish-readiness-1"
      ]
    },
    {
      "id": "AI-AGENT-001",
      "title": "MCP server authentication present",
      "category": "secure_development",
      "assurance": "signal",
      "lifecycle": "experimental",
      "weight": 3,
      "profiles": [
        "ai-agent-baseline-1",
        "appsec-mcp-server-1"
      ]
    },
    {
      "id": "AI-AGENT-002",
      "title": "Agent tool allowlist explicitly defined",
      "category": "secure_development",
      "assurance": "signal",
      "lifecycle": "experimental",
      "weight": 3,
      "profiles": [
        "ai-agent-baseline-1",
        "appsec-agentic-asi-1"
      ]
    },
    {
      "id": "AI-AGENT-003",
      "title": "System prompt registry is versioned and code-reviewed",
      "category": "secure_development",
      "assurance": "signal",
      "lifecycle": "experimental",
      "weight": 2,
      "profiles": [
        "ai-agent-baseline-1"
      ]
    },
    {
      "id": "AI-AGENT-004",
      "title": "Prompt injection / adversarial agent tests present",
      "category": "secure_development",
      "assurance": "signal",
      "lifecycle": "experimental",
      "weight": 2,
      "profiles": [
        "ai-agent-baseline-1"
      ]
    },
    {
      "id": "AI-AGENT-005",
      "title": "Agent output sanitization layer documented",
      "category": "secure_development",
      "assurance": "evidence-backed",
      "lifecycle": "experimental",
      "weight": 2,
      "profiles": [
        "ai-agent-baseline-1"
      ]
    },
    {
      "id": "AI-AGENT-006",
      "title": "Agent rate limiting or quota configuration present",
      "category": "secure_development",
      "assurance": "signal",
      "lifecycle": "experimental",
      "weight": 2,
      "profiles": [
        "ai-agent-baseline-1"
      ]
    },
    {
      "id": "AI-AGENT-007",
      "title": "Agent tool-call audit logging configured",
      "category": "secure_development",
      "assurance": "evidence-backed",
      "lifecycle": "experimental",
      "weight": 3,
      "profiles": [
        "ai-agent-baseline-1"
      ]
    },
    {
      "id": "AI-AGENT-008",
      "title": "Dedicated agent identity or audience-bound authn configured",
      "category": "secure_development",
      "assurance": "signal",
      "lifecycle": "experimental",
      "weight": 2,
      "profiles": [
        "ai-agent-baseline-1"
      ]
    },
    {
      "id": "AI-AGENT-009",
      "title": "Sensitive context excluded from long-term agent memory",
      "category": "secure_development",
      "assurance": "evidence-backed",
      "lifecycle": "experimental",
      "weight": 2,
      "profiles": [
        "ai-agent-baseline-1"
      ]
    },
    {
      "id": "AI-AGENT-010",
      "title": "Model provider/version pinning enforced for agent runtime",
      "category": "secure_development",
      "assurance": "signal",
      "lifecycle": "experimental",
      "weight": 3,
      "profiles": [
        "ai-agent-baseline-1"
      ]
    },
    {
      "id": "OSPS-SCORECARD-V6-001",
      "title": "OpenSSF Scorecard v6 OSPS Baseline conformance evidence present",
      "category": "supply_chain",
      "assurance": "evidence-backed",
      "lifecycle": "experimental",
      "weight": 2,
      "profiles": [
        "osps-baseline-2026-1"
      ]
    },
    {
      "id": "LLM-AI-ACT-DEV-002",
      "title": "AI system development/design and training-data description documented (Annex IV section 2)",
      "category": "secure_development",
      "assurance": "evidence-backed",
      "lifecycle": "experimental",
      "weight": 2,
      "profiles": [
        "cra-eu-ai-act-art11-1"
      ]
    },
    {
      "id": "LLM-AI-ACT-PERF-004",
      "title": "AI system performance metrics and accuracy documented (Annex IV section 4)",
      "category": "secure_development",
      "assurance": "evidence-backed",
      "lifecycle": "experimental",
      "weight": 2,
      "profiles": [
        "cra-eu-ai-act-art11-1"
      ]
    },
    {
      "id": "LLM-AI-ACT-CYBER-006",
      "title": "AI system cybersecurity measures documented (Annex IV section 6)",
      "category": "secure_development",
      "assurance": "evidence-backed",
      "lifecycle": "experimental",
      "weight": 3,
      "profiles": [
        "cra-eu-ai-act-art11-1"
      ]
    },
    {
      "id": "LLM-AI-ACT-CHANGE-007",
      "title": "AI system lifecycle change record documented (Annex IV section 7)",
      "category": "secure_development",
      "assurance": "evidence-backed",
      "lifecycle": "experimental",
      "weight": 2,
      "profiles": [
        "cra-eu-ai-act-art11-1"
      ]
    },
    {
      "id": "LLM-AI-ACT-STD-008",
      "title": "Applied harmonised standards listed (Annex IV section 7)",
      "category": "secure_development",
      "assurance": "evidence-backed",
      "lifecycle": "experimental",
      "weight": 1,
      "profiles": [
        "cra-eu-ai-act-art11-1"
      ]
    },
    {
      "id": "LLM-AI-ACT-PMM-009",
      "title": "Post-market monitoring plan documented (Annex IV section 8)",
      "category": "secure_development",
      "assurance": "evidence-backed",
      "lifecycle": "experimental",
      "weight": 2,
      "profiles": [
        "cra-eu-ai-act-art11-1"
      ]
    },
    {
      "id": "CRA-ART13-SBD-001",
      "title": "Security-by-design intent declared (CRA Article 13)",
      "category": "governance",
      "assurance": "signal",
      "lifecycle": "experimental",
      "weight": 2,
      "profiles": [
        "cra-eu-ready-2-1"
      ]
    },
    {
      "id": "CRA-ART13-DEFAULTS-002",
      "title": "Secure-by-default configuration documented (CRA Article 13)",
      "category": "governance",
      "assurance": "signal",
      "lifecycle": "experimental",
      "weight": 2,
      "profiles": [
        "cra-eu-ready-2-1"
      ]
    },
    {
      "id": "CRA-ART14-CSAF-001",
      "title": "CSAF advisory feed present (CRA Article 14 reporting readiness)",
      "category": "governance",
      "assurance": "signal",
      "lifecycle": "experimental",
      "weight": 2,
      "profiles": [
        "cra-eu-ready-2-1"
      ]
    },
    {
      "id": "CRA-ART14-COORD-002",
      "title": "Coordinated vulnerability disclosure policy documented (CRA Article 14)",
      "category": "governance",
      "assurance": "signal",
      "lifecycle": "experimental",
      "weight": 2,
      "profiles": [
        "cra-eu-ready-2-1"
      ]
    },
    {
      "id": "CRA-PRODUCT-CLASS-001",
      "title": "CRA product classification declared (Implementing Reg (EU) 2025/2392)",
      "category": "governance",
      "assurance": "signal",
      "lifecycle": "experimental",
      "weight": 1,
      "profiles": [
        "cra-eu-ready-2-1"
      ]
    },
    {
      "id": "CISA-SBD-VDP-001",
      "title": "Published vulnerability disclosure policy signal (RFC 9116 security.txt / SECURITY.md, ISO/IEC 29147)",
      "category": "governance",
      "assurance": "signal",
      "lifecycle": "experimental",
      "weight": 2,
      "profiles": [
        "oss-publish-readiness-1"
      ]
    },
    {
      "id": "CISA-SBD-CVE-003",
      "title": "Published advisories carry CWE identifiers (ISO/IEC 30111 handling hygiene)",
      "category": "governance",
      "assurance": "signal",
      "lifecycle": "experimental",
      "weight": 1,
      "profiles": [
        "oss-publish-readiness-1"
      ]
    },
    {
      "id": "CISA-SBD-SECRETS-005",
      "title": "Default-credential / hardcoded-secret hygiene composed from secret-scan evidence",
      "category": "governance",
      "assurance": "evidence-backed",
      "lifecycle": "experimental",
      "weight": 2,
      "profiles": [
        "oss-publish-readiness-1"
      ]
    },
    {
      "id": "SCA-KEV-001",
      "title": "No dependency CVE present in the CISA KEV catalog (SARIF kev property)",
      "category": "vulnerability_management",
      "assurance": "evidence-backed",
      "lifecycle": "experimental",
      "weight": 3,
      "profiles": [
        "appsec-sast-sca-1"
      ]
    },
    {
      "id": "SCA-EPSS-001",
      "title": "No high-EPSS high-severity dependency CVE unaddressed (SARIF epss_score property)",
      "category": "vulnerability_management",
      "assurance": "evidence-backed",
      "lifecycle": "experimental",
      "weight": 2,
      "profiles": [
        "appsec-sast-sca-1"
      ]
    },
    {
      "id": "SLSA-SRC-006",
      "title": "Signed commits required (SLSA Source L2)",
      "category": "supply_chain",
      "assurance": "evidence-backed",
      "lifecycle": "experimental",
      "weight": 3,
      "profiles": [
        "slsa-source-l2-1"
      ]
    },
    {
      "id": "SLSA-SRC-007",
      "title": "Two-party review threshold enforced (SLSA Source L2)",
      "category": "supply_chain",
      "assurance": "evidence-backed",
      "lifecycle": "experimental",
      "weight": 2,
      "profiles": [
        "slsa-source-l2-1"
      ]
    },
    {
      "id": "SLSA-SRC-008",
      "title": "Source-change audit log streamed externally (SLSA Source L2)",
      "category": "supply_chain",
      "assurance": "evidence-backed",
      "lifecycle": "experimental",
      "weight": 2,
      "profiles": [
        "slsa-source-l2-1"
      ]
    },
    {
      "id": "MCP-TOOL-HASH-001",
      "title": "MCP tool descriptions hash-pinned (tool-poisoning defense)",
      "category": "secure_development",
      "assurance": "signal",
      "lifecycle": "experimental",
      "weight": 3,
      "profiles": [
        "appsec-agentic-asi-1",
        "appsec-mcp-server-1"
      ]
    },
    {
      "id": "MCP-CONFIRM-001",
      "title": "MCP destructive operations require explicit confirmation",
      "category": "secure_development",
      "assurance": "signal",
      "lifecycle": "experimental",
      "weight": 2,
      "profiles": [
        "appsec-agentic-asi-1",
        "appsec-mcp-server-1"
      ]
    },
    {
      "id": "MCP-EGRESS-001",
      "title": "MCP server egress allowlist documented",
      "category": "secure_development",
      "assurance": "signal",
      "lifecycle": "experimental",
      "weight": 2,
      "profiles": [
        "appsec-mcp-server-1"
      ]
    },
    {
      "id": "MCP-INJECTION-TEST-001",
      "title": "MCP prompt-injection / tool-poisoning tests present",
      "category": "secure_development",
      "assurance": "signal",
      "lifecycle": "experimental",
      "weight": 1,
      "profiles": [
        "appsec-mcp-server-1"
      ]
    },
    {
      "id": "MCP-SCOPE-001",
      "title": "MCP per-tool least-privilege scope documented",
      "category": "secure_development",
      "assurance": "signal",
      "lifecycle": "experimental",
      "weight": 2,
      "profiles": [
        "appsec-mcp-server-1"
      ]
    },
    {
      "id": "AGENT-ASI-GOAL-001",
      "title": "Agent goal/system-prompt version-controlled and integrity-checked (ASI01)",
      "category": "secure_development",
      "assurance": "signal",
      "lifecycle": "experimental",
      "weight": 2,
      "profiles": [
        "appsec-agentic-asi-1"
      ]
    },
    {
      "id": "AGENT-ASI-TOOL-002",
      "title": "Agent tool allowlist with per-tool least privilege documented (ASI02)",
      "category": "secure_development",
      "assurance": "signal",
      "lifecycle": "experimental",
      "weight": 2,
      "profiles": [
        "appsec-agentic-asi-1"
      ]
    },
    {
      "id": "AGENT-ASI-MEMORY-006",
      "title": "Agent persistent-memory purge / poisoning policy documented (ASI06)",
      "category": "secure_development",
      "assurance": "signal",
      "lifecycle": "experimental",
      "weight": 2,
      "profiles": [
        "appsec-agentic-asi-1"
      ]
    },
    {
      "id": "AGENT-ASI-INTER-007",
      "title": "Inter-agent communication mutual authentication signal (ASI07)",
      "category": "secure_development",
      "assurance": "signal",
      "lifecycle": "experimental",
      "weight": 2,
      "profiles": [
        "appsec-agentic-asi-1"
      ]
    },
    {
      "id": "AGENT-ASI-CONFIRM-009",
      "title": "Human checkpoint required for destructive agent operations (ASI09)",
      "category": "secure_development",
      "assurance": "signal",
      "lifecycle": "experimental",
      "weight": 2,
      "profiles": [
        "appsec-agentic-asi-1"
      ]
    },
    {
      "id": "AGENT-ASI-EXEC-005",
      "title": "Agent code-execution sandboxing / isolation documented (ASI05)",
      "category": "secure_development",
      "assurance": "signal",
      "lifecycle": "experimental",
      "weight": 2,
      "profiles": [
        "appsec-agentic-asi-1"
      ]
    },
    {
      "id": "AGENT-ASI-CASCADE-008",
      "title": "Agent cascading-failure guards documented (iteration/recursion caps, breakers) (ASI08)",
      "category": "secure_development",
      "assurance": "signal",
      "lifecycle": "experimental",
      "weight": 2,
      "profiles": [
        "appsec-agentic-asi-1"
      ]
    },
    {
      "id": "AGENT-ASI-ROGUE-010",
      "title": "Agent inventory / monitoring for rogue-agent detection documented (ASI10)",
      "category": "secure_development",
      "assurance": "signal",
      "lifecycle": "experimental",
      "weight": 2,
      "profiles": [
        "appsec-agentic-asi-1"
      ]
    },
    {
      "id": "GH-EGRESS-NATIVE-001",
      "title": "GitHub Actions native egress firewall policy declared",
      "category": "ci_cd",
      "assurance": "signal",
      "lifecycle": "experimental",
      "weight": 2,
      "profiles": [
        "oss-publish-readiness-1"
      ]
    },
    {
      "id": "GH-WF-LOCKFILE-001",
      "title": "GitHub Actions workflow lockfile present (action SHA pinning)",
      "category": "ci_cd",
      "assurance": "signal",
      "lifecycle": "experimental",
      "weight": 2,
      "profiles": [
        "oss-publish-readiness-1"
      ]
    },
    {
      "id": "CONT-DISTROLESS-001",
      "title": "Container base image is distroless / minimal (Chainguard, Wolfi, distroless, scratch)",
      "category": "container",
      "assurance": "signal",
      "lifecycle": "experimental",
      "weight": 2,
      "profiles": [
        "container-baseline-1"
      ]
    },
    {
      "id": "SCANNER-INTEGRITY-001",
      "title": "Scanner actions pinned by SHA (post-Trivy supply-chain defense)",
      "category": "ci_cd",
      "assurance": "signal",
      "lifecycle": "experimental",
      "weight": 2,
      "profiles": [
        "oss-publish-readiness-1"
      ]
    }
  ]
};
