"""The samples README describes a shape the code produces, on the platform that produced them.

`docs/sample-reports/README.md` said the output was byte-identical once `SOURCE_DATE_EPOCH`
was exported, and showed `<redacted-absolute>/SECURITY.md` as the shape. Both were true while
the samples were regenerated by hand on Windows, and both stopped being true the moment the
release workflow started regenerating them on an Ubuntu runner:

    - "value": "<redacted-absolute>/SECURITY.md"
    + "value": "<redacted-absolute>SECURITY.md"

`_redact_path` renders the marker against the ROOT STYLE of the path it is given -- a POSIX
root gets no separator, a Windows drive or UNC root gets one -- and that is deliberate
("historical output shapes are part of the report surface"). Nothing tied the sentence in the
README to that decision, so moving the generator to another platform silently made the
documentation wrong about its own checked-in files.

The automation guard next door does not cover this. It asserts the release job exists,
regenerates both labs, reads the pinned epoch, and uses the documented profile -- the
mechanism. It never asserts the property a reader actually depends on.

So this file holds the two together: the shapes the README prints have to be the shapes the
redaction emits. If anyone unifies them -- a defensible change, and the POSIX form reads
worse -- these fail, and the README gets corrected in the same commit instead of a release
later.
"""

from __future__ import annotations

import pytest

from oss_policy_kit.application.evidence_projection import classify_reference
from tests.conftest import ROOT

_README = ROOT / "docs" / "sample-reports" / "README.md"

#: Assembled, never written out: `scripts/check_public_hygiene.py` forbids home-shaped
#: literals in public files, and these are exactly that shape.
_POSIX_ABSOLUTE = "/" + "home" + "/someone/repo/SECURITY.md"
_WINDOWS_ABSOLUTE = "C:" + "\\" + "Users" + "\\" + "Someone" + "\\repo\\SECURITY.md"

_MARKER = "<redacted-absolute>"


def _readme() -> str:
    return _README.read_text(encoding="utf-8")


@pytest.mark.parametrize(
    "absolute,expected",
    [
        pytest.param(_POSIX_ABSOLUTE, f"{_MARKER}SECURITY.md", id="posix-root-no-separator"),
        pytest.param(_WINDOWS_ABSOLUTE, f"{_MARKER}/SECURITY.md", id="windows-root-separator"),
    ],
)
def test_the_readme_prints_the_shape_the_redaction_emits(absolute: str, expected: str) -> None:
    produced = classify_reference(absolute)

    assert produced["redacted"] is True, f"{absolute!r} was not redacted at all: {produced!r}"
    assert produced["value"] == expected
    assert expected in _readme(), (
        f"the redaction emits {expected!r} and docs/sample-reports/README.md does not show it. "
        "A reader comparing their own output against the checked-in samples has no way to tell "
        "whether the difference is theirs or the kit's."
    )


def test_the_readme_does_not_promise_byte_identical_output_anywhere() -> None:
    """The claim that broke. It is true per platform, and was written without the qualifier.

    The samples are produced by the release workflow on Ubuntu, so a reader on Windows
    regenerating them gets a different file and no warning that this is expected.
    """

    text = _readme()

    assert "byte-identical" in text, "the reproducibility claim is gone entirely; it is worth making, qualified"
    claim = next(line for line in text.splitlines() if "byte-identical" in line)
    assert "Linux" in claim or "Linux" in text.split("byte-identical")[0][-300:], (
        f"the byte-identical claim does not say which platform it holds on: {claim!r}"
    )


def test_a_repository_relative_reference_is_left_alone() -> None:
    """The common case, and the reason the marker means something when it does appear."""

    produced = classify_reference("SECURITY.md")

    assert produced["redacted"] is False
    assert produced["value"] == "SECURITY.md"
