"""The release branch has to regenerate the sample reports without a human.

`test_sample_reports_match_the_shipped_contract` requires the checked-in samples to carry the
version of the tree they sit in. release-please bumps the tree and cannot regenerate them, so
every release branch arrived with that guard failing. It happened on v10.0.16 and again on
v10.0.17 before the automation existed -- twice is not an accident, it is a step in the
release that nobody wrote down.

The shortcut it invites is editing the version string by hand, which is what the guard's own
message forbids, because that claims a freshness the file does not have.

This holds the automation to the parts that can rot silently. If the job stops regenerating,
nothing fails until the next release branch blocks, and by then the person cutting the release
is looking for a shortcut again. So the properties are asserted here instead:

- the job exists and both labs are regenerated, not just one;
- the pinned epoch is READ from the document that defines it. Repeating the number in the
  workflow would make it a second source of truth, and the whole reason the epoch is pinned
  is that the output must be byte-identical between runs;
- the profile matches the one the documented commands use, so the automation cannot quietly
  regenerate the samples against a different profile than the README tells a reader to use.
"""

from __future__ import annotations

import re

import yaml

from tests.conftest import ROOT

_WORKFLOW = ROOT / ".github" / "workflows" / "release-please.yml"
_SAMPLES_README = ROOT / "docs" / "sample-reports" / "README.md"

#: The labs the README documents, which the automation has to keep in step.
_LABS = ("examples/hardened-repo", "examples/vulnerable-repo")


def _regeneration_script() -> str:
    """The `run:` block of the step that regenerates the samples."""

    document = yaml.safe_load(_WORKFLOW.read_text(encoding="utf-8"))
    scripts = [
        str(step.get("run", ""))
        for job in (document.get("jobs") or {}).values()
        for step in (job.get("steps") or [])
        if "oss_policy_kit evaluate" in str(step.get("run", "")) and "sample-reports" in str(step.get("run", ""))
    ]
    assert len(scripts) == 1, (
        f"expected exactly one step regenerating the sample reports, found {len(scripts)}. "
        "Two of them would race on the same files; none means the release branch is back to "
        "needing a human."
    )
    return scripts[0]


def test_both_sample_labs_are_regenerated() -> None:
    script = _regeneration_script()

    for lab in _LABS:
        assert lab in script, (
            f"{lab} is not regenerated by the release workflow. Regenerating one lab and not "
            "the other leaves half the samples stamped with the previous version, which fails "
            "the version guard just as surely as regenerating neither."
        )


def test_the_pinned_epoch_is_read_from_the_document_that_defines_it() -> None:
    script = _regeneration_script()

    assert "docs/sample-reports/README.md" in script, (
        "the workflow no longer reads SOURCE_DATE_EPOCH from docs/sample-reports/README.md. "
        "That file is where the pin is defined and explained."
    )

    documented = re.search(r"SOURCE_DATE_EPOCH=(\d+)", _SAMPLES_README.read_text(encoding="utf-8"))
    assert documented, "docs/sample-reports/README.md no longer pins SOURCE_DATE_EPOCH at all"

    assert documented.group(1) not in script, (
        f"the epoch {documented.group(1)} is hardcoded in the workflow as well as documented "
        "in docs/sample-reports/README.md. Two copies of a pin are two things to drift; the "
        "workflow is meant to read it from the README."
    )


def test_the_automation_uses_the_profile_the_readme_documents() -> None:
    script = _regeneration_script()
    readme = _SAMPLES_README.read_text(encoding="utf-8")

    documented = set(re.findall(r"--profile\s+([\w-]+)", readme))
    assert documented, "docs/sample-reports/README.md documents no --profile to compare against"

    used = set(re.findall(r"--profile\s+([\w-]+)", script))
    assert used == documented, (
        f"the release workflow regenerates with {sorted(used)} while the README documents "
        f"{sorted(documented)}. The samples would then be produced by a different profile than "
        "the one a reader is told to reproduce them with."
    )
